### PR TITLE
Fix timestamps

### LINKED ISSUE #668: pack build with the --timestamps flag doesn't add timestamps to container logs
### Summary

`pack build` with the `--timestamps` flag doesn't add timestamps to container logs.

---

##### Steps

1. `pack build <my-image> --timestamps`

##### Current behavior
Only one line has a timestamp:
```
pack build --builder gcr.io/paketo-buildpacks/builder:base -p ./target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar petclinic --timestamps --no-pull
---> DETECTING
5 of 15 buildpacks participating
paketo-buildpacks/bellsoft-liberica 2.7.3
paketo-buildpacks/executable-jar    1.2.5
paketo-buildpacks/apache-tomcat     1.2.2
paketo-buildpacks/dist-zip          1.3.3
paketo-buildpacks/spring-boot       1.5.5
---> ANALYZING
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:class-counter" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:java-security-properties" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:jre" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:jvmkill" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:link-local-dns" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:memory-calculator" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:openssl-security-provider" from app image
Restoring metadata for "paketo-buildpacks/bellsoft-liberica:security-providers-configurer" from app image
Restoring metadata for "paketo-buildpacks/executable-jar:class-path" from app image
---> RESTORING
---> BUILDING

Paketo BellSoft Liberica Buildpack 2.7.3
  https://github.com/paketo-buildpacks/bellsoft-liberica
  Build Configuration:
    $BP_JVM_VERSION              11.* (default)            the Java version
  Launch Configuration:
    $BPL_JVM_HEAD_ROOM           0 (default)               the headroom in memory calculation
    $BPL_JVM_LOADED_CLASS_COUNT  35% of classes (default)  the number of loaded classes in memory calculation
    $BPL_JVM_THREAD_COUNT        250 (default)             the number of threads in memory calculation
  BellSoft Liberica JRE 11.0.7: Reusing cached layer
  Memory Calculator 4.0.0: Reusing cached layer
  Class Counter: Reusing cached layer
  JVMKill Agent 1.16.0: Reusing cached layer
  Link-Local DNS: Reusing cached layer
  Java Security Properties: Reusing cached layer
  Security Providers Configurer: Reusing cached layer
  OpenSSL Certificate Loader: Reusing cached layer

Paketo Executable JAR Buildpack 1.2.5
  Process types:
    executable-jar: java -cp "${CLASSPATH}" ${JAVA_OPTS} org.springframework.boot.loader.JarLauncher
    task:           java -cp "${CLASSPATH}" ${JAVA_OPTS} org.springframework.boot.loader.JarLauncher
    web:            java -cp "${CLASSPATH}" ${JAVA_OPTS} org.springframework.boot.loader.JarLauncher

Paketo Spring Boot Buildpack 1.5.5
  Image labels:
    org.opencontainers.image.title
    org.opencontainers.image.version
    org.springframework.boot.spring-configuration-metadata.json
    org.springframework.boot.version
---> EXPORTING
Reusing layer 'launcher'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:class-counter'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:java-security-properties'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:jre'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:jvmkill'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:link-local-dns'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:memory-calculator'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:openssl-security-provider'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:security-providers-configurer'
Reusing layer 'paketo-buildpacks/executable-jar:class-path'
Reusing 1/1 app layer(s)
Reusing layer 'config'
*** Images (3186002c2a56):
      index.docker.io/library/petclinic:latest
2020/06/01 14:14:35.147535 Successfully built image petclinic
```

##### Expected behavior

Every line has a timestamp.

---

##### pack info

```
pack report
Pack:
  Version:  0.11.0+git-2cf2c34.build-610
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.5
```

### PR DESCRIPTION
**Pull request by dfreilich**
Create a TimeWriter passed when `--timestamps` is passed in, allowing timestamps to be passed through the downloader and lifecycle. This doesn't change any output when `--timestamps` is not used; however, it does strip the nice line animation when downloading an image. 

Fix #668 

Sample output for `pack build --timestamps`:
<details>
<summary>Click here to expand:</summary>
 
```
 $  out/pack build test1 -p ../paketo-builder/tiny-fixtures/go_mod_app/ --timestamps
2020/06/04 17:29:24.900719 full-cf:
2020/06/04 17:29:24.900944 Pulling from paketo-buildpacks/builder
2020/06/04 17:29:24.901311 Digest: sha256:bcd8d82b94cc444572dcd75c861ce8f0418931e54ab3ac4348ae359603104782
2020/06/04 17:29:24.901382 Status: Image is up to date for gcr.io/paketo-buildpacks/builder:full-cf
2020/06/04 17:29:27.488348 full-cnb-cf:
2020/06/04 17:29:27.488394 Pulling from paketo-buildpacks/run
2020/06/04 17:29:27.489346 Digest: sha256:817d3a21025ea69104b4d257a8ed296b9a335bc8d181ed4649e77429c982578b
2020/06/04 17:29:27.489923 Status: Image is up to date for gcr.io/paketo-buildpacks/run:full-cnb-cf
2020/06/04 17:29:28.304662 ===> DETECTING
2020/06/04 17:29:28.431713 paketo-buildpacks/go-compiler 0.0.156
2020/06/04 17:29:28.431745 paketo-buildpacks/go-mod      0.0.126
2020/06/04 17:29:28.431766 ===> ANALYZING
2020/06/04 17:29:28.457743 Previous image with name "index.docker.io/library/test1:latest" not found
2020/06/04 17:29:28.457764 ===> RESTORING
2020/06/04 17:29:28.457768 ===> BUILDING
2020/06/04 17:29:28.462158 Go Compiler Buildpack 0.0.156
2020/06/04 17:29:28.462189   Resolving Go version
2020/06/04 17:29:28.462201     Candidate version sources (in priority order):
2020/06/04 17:29:28.462209       <unknown> -> ""
2020/06/04 17:29:28.462218
2020/06/04 17:29:28.462224     Selected Go version (using <unknown>): 1.13.12
2020/06/04 17:29:28.462228
2020/06/04 17:29:28.462233   Executing build process
2020/06/04 17:29:28.462236     Installing Go 1.13.12
2020/06/04 17:29:35.107793       Completed in 6.651s
2020/06/04 17:29:35.150966
2020/06/04 17:29:35.150990 Go Mod Buildpack 0.0.126
2020/06/04 17:29:35.150995 Setting environment variables
2020/06/04 17:29:35.150999   : Contributing to layer
2020/06/04 17:29:35.860174 go: finding github.com/BurntSushi/toml v0.3.1
2020/06/04 17:29:35.880518 go: finding github.com/satori/go.uuid v1.2.0
2020/06/04 17:29:35.962607 go-online
2020/06/04 17:29:35.964173   : Contributing to layer
2020/06/04 17:29:35.964198 Running `go install`
2020/06/04 17:29:46.628859   : Contributing to layer
2020/06/04 17:29:46.629286 Contributing start command
2020/06/04 17:29:46.629303   Process types:
2020/06/04 17:29:46.629460     web: /layers/paketo-buildpacks_go-mod/app-binary/bin/go-online
2020/06/04 17:29:46.632714 ===> EXPORTING
2020/06/04 17:29:46.662396 Adding layer 'launcher'
2020/06/04 17:29:46.704559 Adding layer 'paketo-buildpacks/go-mod:app-binary'
2020/06/04 17:29:46.713377 Adding 1/1 app layer(s)
2020/06/04 17:29:46.713863 Adding layer 'config'
2020/06/04 17:29:46.825440 *** Images (435ba2a7670b):
2020/06/04 17:29:46.825464       index.docker.io/library/test1:latest
2020/06/04 17:29:48.363344 Adding cache layer 'paketo-buildpacks/go-compiler:go'
2020/06/04 17:29:48.860892 Adding cache layer 'paketo-buildpacks/go-mod:go-cache'
2020/06/04 17:29:48.891979 Adding cache layer 'paketo-buildpacks/go-mod:go-mod'
2020/06/04 17:29:50.950776 Successfully built image test1
```
</details>

Sample output for `pack build --timestamps` when downloader has to fetch an image: 
<details>
<summary>Click here to expand:</summary>

```
$  out/pack build test1 -p ../paketo-builder/tiny-fixtures/go_mod_app/ --timestamps
2020/06/04 17:30:26.718775 full-cf:
2020/06/04 17:30:26.719019 Pulling from paketo-buildpacks/builder
2020/06/04 17:30:26.719969 f2cf6bcb8426:
2020/06/04 17:30:26.720008 Pulling fs layer
2020/06/04 17:30:26.720057 5fc72bd1c95d:
2020/06/04 17:30:26.720077 Pulling fs layer
2020/06/04 17:30:26.720107 4c1a0023eeb2:
2020/06/04 17:30:26.720155 Pulling fs layer
2020/06/04 17:30:26.720226 c390b0e10e88:
2020/06/04 17:30:26.720285 Pulling fs layer
2020/06/04 17:30:26.720362 b25e50fe7982:
2020/06/04 17:30:26.720428 Pulling fs layer
2020/06/04 17:30:26.720519 537c583653bc:
2020/06/04 17:30:26.720552 Pulling fs layer
2020/06/04 17:30:26.720636 1d4407542c06:
2020/06/04 17:30:26.720653 Pulling fs layer
2020/06/04 17:30:26.720689 505e2464362d:
2020/06/04 17:30:26.720727 Pulling fs layer
2020/06/04 17:30:26.720763 d9fd992fa93b:
2020/06/04 17:30:26.720776 Pulling fs layer
2020/06/04 17:30:26.720798 6c314ef4e51f:
2020/06/04 17:30:26.720825 Pulling fs layer
2020/06/04 17:30:26.720872 a32b6c87b9c5:
2020/06/04 17:30:26.720917 Pulling fs layer
2020/06/04 17:30:26.720972 9d38782cd69d:
2020/06/04 17:30:26.720993 Pulling fs layer
2020/06/04 17:30:26.721043 87b1eb83a4f1:
2020/06/04 17:30:26.721065 Pulling fs layer
2020/06/04 17:30:26.721098 1aa29bf4536d:
2020/06/04 17:30:26.721112 Pulling fs layer
2020/06/04 17:30:26.721166 1b8ffec456d4:
2020/06/04 17:30:26.721183 Pulling fs layer
2020/06/04 17:30:26.721203 2da29b876ba9:
2020/06/04 17:30:26.721215 Pulling fs layer
2020/06/04 17:30:26.721233 8ede1a667ccd:
2020/06/04 17:30:26.721255 Pulling fs layer
2020/06/04 17:30:26.721297 6718e81ed087:
2020/06/04 17:30:26.721344 Pulling fs layer
2020/06/04 17:30:26.721430 831cc6d49dce:
2020/06/04 17:30:26.721448 Pulling fs layer
2020/06/04 17:30:26.721475 ebf3bd764ea6:
2020/06/04 17:30:26.721495 Pulling fs layer
2020/06/04 17:30:26.721518 4ef62affa50b:
2020/06/04 17:30:26.721529 Pulling fs layer
2020/06/04 17:30:26.721546 d89feaffa2fb:
2020/06/04 17:30:26.721560 Pulling fs layer
2020/06/04 17:30:26.721582 2a9814e54919:
2020/06/04 17:30:26.721594 Pulling fs layer
2020/06/04 17:30:26.721614 7a72772b8fe5:
2020/06/04 17:30:26.721630 Pulling fs layer
2020/06/04 17:30:26.721650 12ca1a96de4e:
2020/06/04 17:30:26.721661 Pulling fs layer
2020/06/04 17:30:26.721680 ffe4bf8e929d:
2020/06/04 17:30:26.721692 Pulling fs layer
2020/06/04 17:30:26.721725 ff659ee8423e:
2020/06/04 17:30:26.721739 Pulling fs layer
2020/06/04 17:30:26.721765 55d456274f04:
2020/06/04 17:30:26.721782 Pulling fs layer
2020/06/04 17:30:26.721802 33fc43691f89:
2020/06/04 17:30:26.721844 Pulling fs layer
2020/06/04 17:30:26.721899 a1a98daf958f:
2020/06/04 17:30:26.721933 Pulling fs layer
2020/06/04 17:30:26.722040 c9ed2f6ef64d:
2020/06/04 17:30:26.722072 Pulling fs layer
2020/06/04 17:30:26.722098 05fce2773e92:
2020/06/04 17:30:26.722110 Pulling fs layer
2020/06/04 17:30:26.722142 f4313406ed7c:
2020/06/04 17:30:26.722158 Pulling fs layer
2020/06/04 17:30:26.722181 aaeb1f367d66:
2020/06/04 17:30:26.722239 Pulling fs layer
2020/06/04 17:30:26.722266 235717141686:
2020/06/04 17:30:26.722280 Pulling fs layer
2020/06/04 17:30:26.722328 c31d64e7bebc:
2020/06/04 17:30:26.722354 Pulling fs layer
2020/06/04 17:30:26.722379 1d71f6e6530a:
2020/06/04 17:30:26.722391 Pulling fs layer
2020/06/04 17:30:26.722414 d9c94d50c1ff:
2020/06/04 17:30:26.722427 Pulling fs layer
2020/06/04 17:30:26.722446 d852805df968:
2020/06/04 17:30:26.722457 Pulling fs layer
2020/06/04 17:30:26.722477 9b31e3951e34:
2020/06/04 17:30:26.722489 Pulling fs layer
2020/06/04 17:30:26.722510 0c99a9dc6fa5:
2020/06/04 17:30:26.722523 Pulling fs layer
2020/06/04 17:30:26.722545 20e8a67ca4c3:
2020/06/04 17:30:26.722556 Pulling fs layer
2020/06/04 17:30:26.722576 89732bc75041:
2020/06/04 17:30:26.722589 Pulling fs layer
2020/06/04 17:30:26.722612 c390b0e10e88:
2020/06/04 17:30:26.722624 Waiting
2020/06/04 17:30:26.722649 b25e50fe7982:
2020/06/04 17:30:26.722660 Waiting
2020/06/04 17:30:26.722697 537c583653bc:
2020/06/04 17:30:26.722713 Waiting
2020/06/04 17:30:26.722747 1d4407542c06:
2020/06/04 17:30:26.722757 Waiting
2020/06/04 17:30:26.722775 505e2464362d:
2020/06/04 17:30:26.722803 Waiting
2020/06/04 17:30:26.722875 d9fd992fa93b:
2020/06/04 17:30:26.722892 Waiting
2020/06/04 17:30:26.722919 6c314ef4e51f:
2020/06/04 17:30:26.722935 Waiting
2020/06/04 17:30:26.722956 a32b6c87b9c5:
2020/06/04 17:30:26.723010 Waiting
2020/06/04 17:30:26.723032 9d38782cd69d:
2020/06/04 17:30:26.723043 Waiting
2020/06/04 17:30:26.723064 87b1eb83a4f1:
2020/06/04 17:30:26.723080 Waiting
2020/06/04 17:30:26.723099 1aa29bf4536d:
2020/06/04 17:30:26.723111 Waiting
2020/06/04 17:30:26.723126 1b8ffec456d4:
2020/06/04 17:30:26.723147 Waiting
2020/06/04 17:30:26.723183 2da29b876ba9:
2020/06/04 17:30:26.723199 Waiting
2020/06/04 17:30:26.723223 8ede1a667ccd:
2020/06/04 17:30:26.723239 Waiting
2020/06/04 17:30:26.723261 6718e81ed087:
2020/06/04 17:30:26.723277 Waiting
2020/06/04 17:30:26.723308 831cc6d49dce:
2020/06/04 17:30:26.723317 Waiting
2020/06/04 17:30:26.723830 ebf3bd764ea6:
2020/06/04 17:30:26.723850 Waiting
2020/06/04 17:30:26.723877 4ef62affa50b:
2020/06/04 17:30:26.723886 Waiting
2020/06/04 17:30:26.723899 d89feaffa2fb:
2020/06/04 17:30:26.723905 Waiting
2020/06/04 17:30:26.723915 2a9814e54919:
2020/06/04 17:30:26.723923 Waiting
2020/06/04 17:30:26.723932 7a72772b8fe5:
2020/06/04 17:30:26.723940 Waiting
2020/06/04 17:30:26.723961 12ca1a96de4e:
2020/06/04 17:30:26.723968 Waiting
2020/06/04 17:30:26.723985 ffe4bf8e929d:
2020/06/04 17:30:26.723999 Waiting
2020/06/04 17:30:26.724018 ff659ee8423e:
2020/06/04 17:30:26.724030 Waiting
2020/06/04 17:30:26.724051 55d456274f04:
2020/06/04 17:30:26.724064 Waiting
2020/06/04 17:30:26.724084 33fc43691f89:
2020/06/04 17:30:26.724096 Waiting
2020/06/04 17:30:26.724117 a1a98daf958f:
2020/06/04 17:30:26.724127 Waiting
2020/06/04 17:30:26.724149 c9ed2f6ef64d:
2020/06/04 17:30:26.724161 Waiting
2020/06/04 17:30:26.724181 05fce2773e92:
2020/06/04 17:30:26.724192 Waiting
2020/06/04 17:30:26.724213 d852805df968:
2020/06/04 17:30:26.724227 Waiting
2020/06/04 17:30:26.724248 9b31e3951e34:
2020/06/04 17:30:26.724283 Waiting
2020/06/04 17:30:26.724304 f4313406ed7c:
2020/06/04 17:30:26.724315 Waiting
2020/06/04 17:30:26.724333 0c99a9dc6fa5:
2020/06/04 17:30:26.724344 Waiting
2020/06/04 17:30:26.724365 89732bc75041:
2020/06/04 17:30:26.724376 Waiting
2020/06/04 17:30:26.724397 20e8a67ca4c3:
2020/06/04 17:30:26.724409 Waiting
2020/06/04 17:30:26.724431 aaeb1f367d66:
2020/06/04 17:30:26.724444 Waiting
2020/06/04 17:30:26.724466 1d71f6e6530a:
2020/06/04 17:30:26.724479 Waiting
2020/06/04 17:30:26.724499 235717141686:
2020/06/04 17:30:26.724512 Waiting
2020/06/04 17:30:26.724546 c31d64e7bebc:
2020/06/04 17:30:26.724565 Waiting
2020/06/04 17:30:26.724597 d9c94d50c1ff:
2020/06/04 17:30:26.724618 Waiting
2020/06/04 17:30:27.161751 5fc72bd1c95d:
2020/06/04 17:30:27.161773 Verifying Checksum
2020/06/04 17:30:27.161797 5fc72bd1c95d:
2020/06/04 17:30:27.161818 Download complete
2020/06/04 17:30:27.708601 c390b0e10e88:
2020/06/04 17:30:27.708627 Verifying Checksum
2020/06/04 17:30:27.708651 c390b0e10e88:
2020/06/04 17:30:27.708662 Download complete
2020/06/04 17:30:28.154980 4c1a0023eeb2:
2020/06/04 17:30:28.155056 Download complete
2020/06/04 17:30:28.621065 b25e50fe7982:
2020/06/04 17:30:28.621097 Verifying Checksum
2020/06/04 17:30:28.621480 b25e50fe7982:
2020/06/04 17:30:28.621548 Download complete
2020/06/04 17:30:29.097122 537c583653bc:
2020/06/04 17:30:29.097194 Verifying Checksum
2020/06/04 17:30:29.097245 537c583653bc:
2020/06/04 17:30:29.097290 Download complete
2020/06/04 17:30:30.569819 1d4407542c06:
2020/06/04 17:30:30.569883 Verifying Checksum
2020/06/04 17:30:30.569924 1d4407542c06:
2020/06/04 17:30:30.569957 Download complete
2020/06/04 17:30:32.564823 d9fd992fa93b:
2020/06/04 17:30:32.564859 Verifying Checksum
2020/06/04 17:30:32.564889 d9fd992fa93b:
2020/06/04 17:30:32.564925 Download complete
2020/06/04 17:30:32.966958 505e2464362d:
2020/06/04 17:30:32.966994 Verifying Checksum
2020/06/04 17:30:32.967531 505e2464362d:
2020/06/04 17:30:32.967549 Download complete
2020/06/04 17:30:36.037090 6c314ef4e51f:
2020/06/04 17:30:36.037149 Verifying Checksum
2020/06/04 17:30:36.037189 6c314ef4e51f:
2020/06/04 17:30:36.037204 Download complete
2020/06/04 17:30:36.702402 a32b6c87b9c5:
2020/06/04 17:30:36.702439 Verifying Checksum
2020/06/04 17:30:36.702478 a32b6c87b9c5:
2020/06/04 17:30:36.702578 Download complete
2020/06/04 17:30:38.843412 9d38782cd69d:
2020/06/04 17:30:38.843458 Verifying Checksum
2020/06/04 17:30:38.843663 9d38782cd69d:
2020/06/04 17:30:38.843699 Download complete
2020/06/04 17:30:42.178999 87b1eb83a4f1:
2020/06/04 17:30:42.179070 Verifying Checksum
2020/06/04 17:30:42.180074 87b1eb83a4f1:
2020/06/04 17:30:42.180127 Download complete
2020/06/04 17:30:44.010869 1aa29bf4536d:
2020/06/04 17:30:44.010921 Verifying Checksum
2020/06/04 17:30:44.011029 1aa29bf4536d:
2020/06/04 17:30:44.011061 Download complete
2020/06/04 17:30:45.821376 f2cf6bcb8426:
2020/06/04 17:30:45.821419 Verifying Checksum
2020/06/04 17:30:45.821475 f2cf6bcb8426:
2020/06/04 17:30:45.821500 Download complete
2020/06/04 17:30:46.572327 1b8ffec456d4:
2020/06/04 17:30:46.572376 Verifying Checksum
2020/06/04 17:30:46.572422 1b8ffec456d4:
2020/06/04 17:30:46.572467 Download complete
2020/06/04 17:30:46.788410 2da29b876ba9:
2020/06/04 17:30:46.788443 Verifying Checksum
2020/06/04 17:30:46.788479 2da29b876ba9:
2020/06/04 17:30:46.788494 Download complete
2020/06/04 17:30:46.959842 8ede1a667ccd:
2020/06/04 17:30:46.959891 Verifying Checksum
2020/06/04 17:30:46.960509 8ede1a667ccd:
2020/06/04 17:30:46.960560 Download complete
2020/06/04 17:30:47.629212 6718e81ed087:
2020/06/04 17:30:47.629247 Verifying Checksum
2020/06/04 17:30:47.630483 6718e81ed087:
2020/06/04 17:30:47.630511 Download complete
2020/06/04 17:30:48.163430 831cc6d49dce:
2020/06/04 17:30:48.163480 Verifying Checksum
2020/06/04 17:30:48.163581 831cc6d49dce:
2020/06/04 17:30:48.163605 Download complete
2020/06/04 17:30:48.171336 ebf3bd764ea6:
2020/06/04 17:30:48.171368 Verifying Checksum
2020/06/04 17:30:48.171455 ebf3bd764ea6:
2020/06/04 17:30:48.171474 Download complete
2020/06/04 17:30:49.014656 4ef62affa50b:
2020/06/04 17:30:49.014695 Verifying Checksum
2020/06/04 17:30:49.014767 4ef62affa50b:
2020/06/04 17:30:49.014795 Download complete
2020/06/04 17:30:49.640297 2a9814e54919:
2020/06/04 17:30:49.640336 Verifying Checksum
2020/06/04 17:30:49.640372 2a9814e54919:
2020/06/04 17:30:49.640387 Download complete
2020/06/04 17:30:49.670692 d89feaffa2fb:
2020/06/04 17:30:49.670733 Verifying Checksum
2020/06/04 17:30:49.670779 d89feaffa2fb:
2020/06/04 17:30:49.670806 Download complete
2020/06/04 17:30:50.016048 7a72772b8fe5:
2020/06/04 17:30:50.016086 Download complete
2020/06/04 17:30:50.243489 12ca1a96de4e:
2020/06/04 17:30:50.243520 Verifying Checksum
2020/06/04 17:30:50.243543 12ca1a96de4e:
2020/06/04 17:30:50.243573 Download complete
2020/06/04 17:30:50.548865 ffe4bf8e929d:
2020/06/04 17:30:50.548916 Verifying Checksum
2020/06/04 17:30:50.551331 ffe4bf8e929d:
2020/06/04 17:30:50.551361 Download complete
2020/06/04 17:30:50.962953 ff659ee8423e:
2020/06/04 17:30:50.962986 Verifying Checksum
2020/06/04 17:30:50.963023 ff659ee8423e:
2020/06/04 17:30:50.963040 Download complete
2020/06/04 17:30:51.198098 55d456274f04:
2020/06/04 17:30:51.198132 Verifying Checksum
2020/06/04 17:30:51.198159 55d456274f04:
2020/06/04 17:30:51.198175 Download complete
2020/06/04 17:30:51.511841 33fc43691f89:
2020/06/04 17:30:51.511946 Verifying Checksum
2020/06/04 17:30:51.511995 33fc43691f89:
2020/06/04 17:30:51.512017 Download complete
2020/06/04 17:30:52.021530 a1a98daf958f:
2020/06/04 17:30:52.021564 Verifying Checksum
2020/06/04 17:30:52.021618 a1a98daf958f:
2020/06/04 17:30:52.021636 Download complete
2020/06/04 17:30:52.506288 05fce2773e92:
2020/06/04 17:30:52.506322 Verifying Checksum
2020/06/04 17:30:52.506350 05fce2773e92:
2020/06/04 17:30:52.506365 Download complete
2020/06/04 17:30:52.522113 c9ed2f6ef64d:
2020/06/04 17:30:52.522148 Download complete
2020/06/04 17:30:52.948544 f4313406ed7c:
2020/06/04 17:30:52.948593 Verifying Checksum
2020/06/04 17:30:52.948741 f4313406ed7c:
2020/06/04 17:30:52.948764 Download complete
2020/06/04 17:30:53.447358 aaeb1f367d66:
2020/06/04 17:30:53.447415 Verifying Checksum
2020/06/04 17:30:53.447998 aaeb1f367d66:
2020/06/04 17:30:53.448030 Download complete
2020/06/04 17:30:54.117517 c31d64e7bebc:
2020/06/04 17:30:54.117552 Verifying Checksum
2020/06/04 17:30:54.117584 c31d64e7bebc:
2020/06/04 17:30:54.117627 Download complete
2020/06/04 17:30:54.412703 235717141686:
2020/06/04 17:30:54.412736 Verifying Checksum
2020/06/04 17:30:54.414615 235717141686:
2020/06/04 17:30:54.414655 Download complete
2020/06/04 17:30:56.705253 d9c94d50c1ff:
2020/06/04 17:30:56.705315 Verifying Checksum
2020/06/04 17:30:56.705358 d9c94d50c1ff:
2020/06/04 17:30:56.705387 Download complete
2020/06/04 17:30:56.727183 1d71f6e6530a:
2020/06/04 17:30:56.727230 Verifying Checksum
2020/06/04 17:30:56.728061 1d71f6e6530a:
2020/06/04 17:30:56.728689 Download complete
2020/06/04 17:30:58.028795 0c99a9dc6fa5:
2020/06/04 17:30:58.028838 Verifying Checksum
2020/06/04 17:30:58.028868 0c99a9dc6fa5:
2020/06/04 17:30:58.028886 Download complete
2020/06/04 17:30:58.587074 9b31e3951e34:
2020/06/04 17:30:58.587106 Download complete
2020/06/04 17:30:58.808243 20e8a67ca4c3:
2020/06/04 17:30:58.808277 Verifying Checksum
2020/06/04 17:30:58.808309 20e8a67ca4c3:
2020/06/04 17:30:58.808326 Download complete
2020/06/04 17:30:59.077483 89732bc75041:
2020/06/04 17:30:59.077527 Verifying Checksum
2020/06/04 17:30:59.077561 89732bc75041:
2020/06/04 17:30:59.077572 Download complete
2020/06/04 17:31:01.203635 d852805df968:
2020/06/04 17:31:01.203677 Verifying Checksum
2020/06/04 17:31:01.205072 d852805df968:
2020/06/04 17:31:01.205111 Download complete
2020/06/04 17:31:08.851587 f2cf6bcb8426:
2020/06/04 17:31:08.851611 Pull complete
2020/06/04 17:31:08.962296 5fc72bd1c95d:
2020/06/04 17:31:08.962326 Pull complete
2020/06/04 17:31:09.251815 4c1a0023eeb2:
2020/06/04 17:31:09.251854 Pull complete
2020/06/04 17:31:09.341543 c390b0e10e88:
2020/06/04 17:31:09.341568 Pull complete
2020/06/04 17:31:09.421390 b25e50fe7982:
2020/06/04 17:31:09.421412 Pull complete
2020/06/04 17:31:09.530043 537c583653bc:
2020/06/04 17:31:09.530085 Pull complete
2020/06/04 17:31:09.630341 1d4407542c06:
2020/06/04 17:31:09.630364 Pull complete
2020/06/04 17:31:09.992542 505e2464362d:
2020/06/04 17:31:09.992575 Pull complete
2020/06/04 17:31:10.334545 d9fd992fa93b:
2020/06/04 17:31:10.334567 Pull complete
2020/06/04 17:31:10.767615 6c314ef4e51f:
2020/06/04 17:31:10.767637 Pull complete
2020/06/04 17:31:11.140673 a32b6c87b9c5:
2020/06/04 17:31:11.140697 Pull complete
2020/06/04 17:31:12.826776 9d38782cd69d:
2020/06/04 17:31:12.826801 Pull complete
2020/06/04 17:31:13.098329 87b1eb83a4f1:
2020/06/04 17:31:13.098360 Pull complete
2020/06/04 17:31:13.369741 1aa29bf4536d:
2020/06/04 17:31:13.369780 Pull complete
2020/06/04 17:31:14.146928 1b8ffec456d4:
2020/06/04 17:31:14.146951 Pull complete
2020/06/04 17:31:14.407666 2da29b876ba9:
2020/06/04 17:31:14.407691 Pull complete
2020/06/04 17:31:14.596841 8ede1a667ccd:
2020/06/04 17:31:14.596887 Pull complete
2020/06/04 17:31:14.829620 6718e81ed087:
2020/06/04 17:31:14.829651 Pull complete
2020/06/04 17:31:15.053422 831cc6d49dce:
2020/06/04 17:31:15.053456 Pull complete
2020/06/04 17:31:15.689701 ebf3bd764ea6:
2020/06/04 17:31:15.689728 Pull complete
2020/06/04 17:31:15.986891 4ef62affa50b:
2020/06/04 17:31:15.986944 Pull complete
2020/06/04 17:31:16.247410 d89feaffa2fb:
2020/06/04 17:31:16.247433 Pull complete
2020/06/04 17:31:16.809834 2a9814e54919:
2020/06/04 17:31:16.809856 Pull complete
2020/06/04 17:31:17.079156 7a72772b8fe5:
2020/06/04 17:31:17.079198 Pull complete
2020/06/04 17:31:17.165729 12ca1a96de4e:
2020/06/04 17:31:17.165750 Pull complete
2020/06/04 17:31:17.330026 ffe4bf8e929d:
2020/06/04 17:31:17.330052 Pull complete
2020/06/04 17:31:17.629316 ff659ee8423e:
2020/06/04 17:31:17.629338 Pull complete
2020/06/04 17:31:17.831608 55d456274f04:
2020/06/04 17:31:17.831633 Pull complete
2020/06/04 17:31:18.003380 33fc43691f89:
2020/06/04 17:31:18.003402 Pull complete
2020/06/04 17:31:18.300595 a1a98daf958f:
2020/06/04 17:31:18.300636 Pull complete
2020/06/04 17:31:18.494394 c9ed2f6ef64d:
2020/06/04 17:31:18.494418 Pull complete
2020/06/04 17:31:18.658935 05fce2773e92:
2020/06/04 17:31:18.658957 Pull complete
2020/06/04 17:31:18.842668 f4313406ed7c:
2020/06/04 17:31:18.842693 Pull complete
2020/06/04 17:31:19.032001 aaeb1f367d66:
2020/06/04 17:31:19.032026 Pull complete
2020/06/04 17:31:19.975376 235717141686:
2020/06/04 17:31:19.975400 Pull complete
2020/06/04 17:31:20.142169 c31d64e7bebc:
2020/06/04 17:31:20.142200 Pull complete
2020/06/04 17:31:20.437837 1d71f6e6530a:
2020/06/04 17:31:20.437865 Pull complete
2020/06/04 17:31:20.642634 d9c94d50c1ff:
2020/06/04 17:31:20.642666 Pull complete
2020/06/04 17:31:20.793745 d852805df968:
2020/06/04 17:31:20.793768 Pull complete
2020/06/04 17:31:20.975823 9b31e3951e34:
2020/06/04 17:31:20.975846 Pull complete
2020/06/04 17:31:21.188643 0c99a9dc6fa5:
2020/06/04 17:31:21.188680 Pull complete
2020/06/04 17:31:21.278014 20e8a67ca4c3:
2020/06/04 17:31:21.278035 Pull complete
2020/06/04 17:31:21.358983 89732bc75041:
2020/06/04 17:31:21.359027 Pull complete
2020/06/04 17:31:21.366700 Digest: sha256:bcd8d82b94cc444572dcd75c861ce8f0418931e54ab3ac4348ae359603104782
2020/06/04 17:31:21.369893 Status: Downloaded newer image for gcr.io/paketo-buildpacks/builder:full-cf
2020/06/04 17:31:24.261311 full-cnb-cf:
2020/06/04 17:31:24.261348 Pulling from paketo-buildpacks/run
2020/06/04 17:31:24.261822 f2cf6bcb8426:
2020/06/04 17:31:24.261940 Already exists
2020/06/04 17:31:24.770063 Digest: sha256:817d3a21025ea69104b4d257a8ed296b9a335bc8d181ed4649e77429c982578b
2020/06/04 17:31:24.773611 Status: Downloaded newer image for gcr.io/paketo-buildpacks/run:full-cnb-cf
2020/06/04 17:31:25.849870 ===> DETECTING
2020/06/04 17:31:25.933055 paketo-buildpacks/go-compiler 0.0.156
2020/06/04 17:31:25.933108 paketo-buildpacks/go-mod      0.0.126
2020/06/04 17:31:25.933129 ===> ANALYZING
2020/06/04 17:31:25.967072 Previous image with name "index.docker.io/library/test1:latest" not found
2020/06/04 17:31:25.967112 ===> RESTORING
2020/06/04 17:31:25.967126 ===> BUILDING
2020/06/04 17:31:25.970971 Go Compiler Buildpack 0.0.156
2020/06/04 17:31:25.971001   Resolving Go version
2020/06/04 17:31:25.971010     Candidate version sources (in priority order):
2020/06/04 17:31:25.971017       <unknown> -> ""
2020/06/04 17:31:25.971023
2020/06/04 17:31:25.971912     Selected Go version (using <unknown>): 1.13.12
2020/06/04 17:31:25.971929
2020/06/04 17:31:25.971934   Executing build process
2020/06/04 17:31:25.971940     Installing Go 1.13.12
2020/06/04 17:31:34.454661       Completed in 8.489s
2020/06/04 17:31:34.469151
2020/06/04 17:31:34.469180 Go Mod Buildpack 0.0.126
2020/06/04 17:31:34.469189 Setting environment variables
2020/06/04 17:31:34.469195   : Contributing to layer
2020/06/04 17:31:35.301219 go: finding github.com/BurntSushi/toml v0.3.1
2020/06/04 17:31:35.316926 go: finding github.com/satori/go.uuid v1.2.0
2020/06/04 17:31:35.413577 go-online
2020/06/04 17:31:35.415857   : Contributing to layer
2020/06/04 17:31:35.415892 Running `go install`
2020/06/04 17:31:50.662453   : Contributing to layer
2020/06/04 17:31:50.662482 Contributing start command
2020/06/04 17:31:50.662490   Process types:
2020/06/04 17:31:50.663657     web: /layers/paketo-buildpacks_go-mod/app-binary/bin/go-online
2020/06/04 17:31:50.669526 ===> EXPORTING
2020/06/04 17:31:50.706583 Adding layer 'launcher'
2020/06/04 17:31:50.761176 Adding layer 'paketo-buildpacks/go-mod:app-binary'
2020/06/04 17:31:50.773831 Adding 1/1 app layer(s)
2020/06/04 17:31:50.775014 Adding layer 'config'
2020/06/04 17:31:51.354688 *** Images (435ba2a7670b):
2020/06/04 17:31:51.355059       index.docker.io/library/test1:latest
2020/06/04 17:31:56.285927 Adding cache layer 'paketo-buildpacks/go-compiler:go'
2020/06/04 17:31:57.918469 Adding cache layer 'paketo-buildpacks/go-mod:go-cache'
2020/06/04 17:31:57.981926 Adding cache layer 'paketo-buildpacks/go-mod:go-mod'
2020/06/04 17:31:59.627717 Successfully built image test1
```
</details>

However, when not specifying `--timestamps`, the normal nice image fetching animation is used:
<details>
<summary>Click here to expand:</summary>

```
$  out/pack build test1 -p ../paketo-builder/tiny-fixtures/go_mod_app/
full-cf: Pulling from paketo-buildpacks/builder
f2cf6bcb8426: Pull complete
5fc72bd1c95d: Pull complete
4c1a0023eeb2: Pull complete
c390b0e10e88: Pull complete
b25e50fe7982: Pull complete
537c583653bc: Pull complete
1d4407542c06: Pull complete
505e2464362d: Pull complete
d9fd992fa93b: Pull complete
6c314ef4e51f: Pull complete
a32b6c87b9c5: Pull complete
9d38782cd69d: Pull complete
87b1eb83a4f1: Pull complete
1aa29bf4536d: Pull complete
1b8ffec456d4: Pull complete
2da29b876ba9: Pull complete
8ede1a667ccd: Pull complete
6718e81ed087: Pull complete
831cc6d49dce: Pull complete
ebf3bd764ea6: Pull complete
4ef62affa50b: Pull complete
d89feaffa2fb: Pull complete
2a9814e54919: Pull complete
7a72772b8fe5: Pull complete
12ca1a96de4e: Pull complete
ffe4bf8e929d: Pull complete
ff659ee8423e: Pull complete
55d456274f04: Pull complete
33fc43691f89: Pull complete
a1a98daf958f: Pull complete
c9ed2f6ef64d: Pull complete
05fce2773e92: Pull complete
f4313406ed7c: Pull complete
aaeb1f367d66: Pull complete
235717141686: Pull complete
c31d64e7bebc: Pull complete
1d71f6e6530a: Pull complete
d9c94d50c1ff: Pull complete
d852805df968: Pull complete
9b31e3951e34: Pull complete
0c99a9dc6fa5: Pull complete
20e8a67ca4c3: Pull complete
89732bc75041: Pull complete
Digest: sha256:bcd8d82b94cc444572dcd75c861ce8f0418931e54ab3ac4348ae359603104782
Status: Downloaded newer image for gcr.io/paketo-buildpacks/builder:full-cf
full-cnb-cf: Pulling from paketo-buildpacks/run
f2cf6bcb8426: Already exists
Digest: sha256:817d3a21025ea69104b4d257a8ed296b9a335bc8d181ed4649e77429c982578b
Status: Downloaded newer image for gcr.io/paketo-buildpacks/run:full-cnb-cf
===> DETECTING
paketo-buildpacks/go-compiler 0.0.156
paketo-buildpacks/go-mod      0.0.126
===> ANALYZING
Previous image with name "index.docker.io/library/test1:latest" not found
===> RESTORING
===> BUILDING
Go Compiler Buildpack 0.0.156
  Resolving Go version
    Candidate version sources (in priority order):
      <unknown> -> ""

    Selected Go version (using <unknown>): 1.13.12

  Executing build process
    Installing Go 1.13.12
      Completed in 8.733s

Go Mod Buildpack 0.0.126
Setting environment variables
  : Contributing to layer
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/satori/go.uuid v1.2.0
go-online
  : Contributing to layer
Running `go install`
  : Contributing to layer
Contributing start command
  Process types:
    web: /layers/paketo-buildpacks_go-mod/app-binary/bin/go-online
===> EXPORTING
Adding layer 'launcher'
Adding layer 'paketo-buildpacks/go-mod:app-binary'
Adding 1/1 app layer(s)
Adding layer 'config'
*** Images (435ba2a7670b):
      index.docker.io/library/test1:latest
Adding cache layer 'paketo-buildpacks/go-compiler:go'
Adding cache layer 'paketo-buildpacks/go-mod:go-cache'
Adding cache layer 'paketo-buildpacks/go-mod:go-mod'
Successfully built image test1
```
</details>

### CODE REVIEW

File: internal/logging/logging.go [hunk 1]
```diff
@@ -67,54 +56,74 @@ func NewLogWithWriters(stdout, stderr io.Writer, opts ...func(*LogWithWriters))
...
-		ts := lw.clock().Format(timeFmt)
-		_, _ = fmt.Fprint(writer, appendMissingLineFeed(fmt.Sprintf("%s %s%s", ts, formatLevel(e.Level), e.Message)))
-		return nil
+	_, err := fmt.Fprint(writer, appendMissingLineFeed(fmt.Sprintf("%s%s", formatLevel(e.Level), e.Message)))
+
+	return err
+}
+
+// WriterForLevel returns a Writer for the given logging.Level
+func (lw *LogWithWriters) WriterForLevel(level logging.Level) io.Writer {
```
Comment (yaelharel) [inline internal/logging/logging.go:85]: Since it's a public function and you changed its return value in some cases, just wanted to be sure that you checked that no one else, except `HandleLog` (and some tests) is using it.

Comment (dfreilich) [reply internal/logging/logging.go:85]: It's a public func, but inside `internal`, so I'm not worried about external users. We do use WriterForLevel in a few places, but the change only added time to the error message, which seemed like a worthwhile goal.
