### PR TITLE
Overwrite permissions of zip files for FAT jars

### LINKED ISSUE #464: Permission denied within FAT formatted jars
### Summary
Certain `.jar` files are not usable by `pack` as application input.

After a bit of research it was determined that the jar files in question are lacking the necessary permissions and/or directory flag which is likely a result of tooling packaging the jar in `DOS` format. See `fat` vs `unx` annotation below.

##### Failing JAR zipinfo
```
zipinfo -m /Users/javier.romero/Downloads/webgoat-container-7.1-exec.jar | grep "META-INF/\$"
-rw----     2.0 fat        0 bl  0% defN 16-Nov-18 16:51 META-INF/
-rw----     2.0 fat        0 bl  0% defN 16-Nov-18 16:51 META-INF/
-rw----     2.0 fat        0 bl  0% defN 16-Nov-18 16:51 META-INF/
-rw----     2.0 fat        0 bl  0% defN 16-Nov-18 16:51 META-INF/
```

##### Working JAR zipinfo

```
zipinfo -m target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar | grep "META-INF/\$"
drwxr-xr-x  2.0 unx        0 bX  0% defN 20-Jan-16 14:06 META-INF/
```

#### References
- https://superuser.com/questions/898481/how-to-create-a-zip-file-with-files-in-fat-format-on-linux

---

#### Detect `fat` file type

If possible when iterating through files in a zip/jar file detect whether we are working with `fat` or `unix` file format. If `fat`, then apply necessary permissions to prevent issue. Otherwise, preserve permissions.

---

##### Steps
1. Download [WebGoat 7.1 exec jar](https://github.com/WebGoat/WebGoat/releases/tag/7.1) 
2. Run:
```
pack build bad-jar-app --builder cloudfoundry/cnb:cflinuxfs3 --path ~/Downloads/webgoat-container-7.1-exec.jar  --verbose
```
3. Notice an error:
```
Status: Downloaded newer image for cloudfoundry/cnb:cflinuxfs3
Selected run image cloudfoundry/run:full-cnb
Pulling image cloudfoundry/run:full-cnb
full-cnb: Pulling from cloudfoundry/run
23fa4234ec28: Pull complete
Digest: sha256:e0fe376bf01ee13c6d45462656ea8ef6cd446132951956ee12a2887f8e0df774
Status: Downloaded newer image for cloudfoundry/run:full-cnb
Using build cache volume pack-cache-ee0406bba513.build
===> DETECTING
[detector] ======== Output: org.cloudfoundry.jvmapplication@v1.0.126 ========
[detector]
[detector] Cloud Foundry JVM Application Buildpack v1.0.126
[detector]   lstat /workspace/META-INF/DEPENDENCIES: permission denied
[detector] ======== Output: org.cloudfoundry.jdbc@v1.0.168 ========
[detector]
[detector] Cloud Foundry JDBC Buildpack v1.0.168
[detector]   lstat /workspace/META-INF/DEPENDENCIES: permission denied
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.openjdk@v1.0.90
[detector] skip: org.cloudfoundry.buildsystem@v1.0.213
[detector] err:  org.cloudfoundry.jvmapplication@v1.0.126 (102)
[detector] pass: org.cloudfoundry.tomcat@v1.1.91
[detector] pass: org.cloudfoundry.springboot@v1.0.175
[detector] pass: org.cloudfoundry.distzip@v1.0.160
[detector] skip: org.cloudfoundry.procfile@v1.0.65
[detector] skip: org.cloudfoundry.azureapplicationinsights@v1.0.166
[detector] skip: org.cloudfoundry.debug@v1.1.35
[detector] skip: org.cloudfoundry.googlestackdriver@v1.0.113
[detector] err:  org.cloudfoundry.jdbc@v1.0.168 (102)
[detector] skip: org.cloudfoundry.jmx@v1.0.169
[detector] pass: org.cloudfoundry.springautoreconfiguration@v1.0.176
[detector] ======== Output: org.cloudfoundry.yarn@0.0.94 ========
[detector] no "yarn.lock" found at: /workspace/yarn.lock
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.node-engine@0.0.133
[detector] fail: org.cloudfoundry.yarn@0.0.94
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.node-engine@0.0.133
[detector] fail: org.cloudfoundry.npm@0.0.83
[detector] ======== Output: org.cloudfoundry.pipenv@0.0.38 ========
[detector] no Pipfile found
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.python-runtime@0.0.57
[detector] skip: org.cloudfoundry.pipenv@0.0.38
[detector] pass: org.cloudfoundry.pip@0.0.53
[detector] Resolving plan... (try #1)
[detector] skip: org.cloudfoundry.pip@0.0.53 requires requirements
[detector] fail: org.cloudfoundry.python-runtime@0.0.57 provides unused python
[detector] ======== Results ========
[detector] fail: org.cloudfoundry.conda@0.0.37
[detector] ======== Output: org.cloudfoundry.go-mod@0.0.58 ========
[detector] no "go.mod" found at: /workspace/go.mod
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.go-compiler@0.0.55
[detector] fail: org.cloudfoundry.go-mod@0.0.58
[detector] ======== Output: org.cloudfoundry.dep@0.0.64 ========
[detector] failed detection: no Gopkg.toml found at root level
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.go-compiler@0.0.55
[detector] fail: org.cloudfoundry.dep@0.0.64
[detector] ======== Output: org.cloudfoundry.dotnet-core-build@0.0.55 ========
[detector] no proj file found
[detector] ======== Output: org.cloudfoundry.dotnet-core-conf@0.0.98 ========
[detector] *.runtimeconfig.json file not found and expecting only a single *.csproj file in the app directory
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.node-engine@0.0.133
[detector] pass: org.cloudfoundry.icu@0.0.25
[detector] pass: org.cloudfoundry.dotnet-core-runtime@0.0.106
[detector] pass: org.cloudfoundry.dotnet-core-aspnet@0.0.97
[detector] pass: org.cloudfoundry.dotnet-core-sdk@0.0.99
[detector] skip: org.cloudfoundry.dotnet-core-build@0.0.55
[detector] fail: org.cloudfoundry.dotnet-core-conf@0.0.98
[detector] ======== Output: org.cloudfoundry.php-composer@0.0.16 ========
[detector] no "composer.json" found in the following locations: [/workspace/composer.json /workspace/htdocs/composer.json]
[detector] ======== Output: org.cloudfoundry.php-web@0.0.24 ========
[detector] failure accessing a path "/workspace/META-INF/DEPENDENCIES": lstat /workspace/META-INF/DEPENDENCIES: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/LICENSE": lstat /workspace/META-INF/LICENSE: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/LICENSE.txt": lstat /workspace/META-INF/LICENSE.txt: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/MANIFEST.MF": lstat /workspace/META-INF/MANIFEST.MF: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/NOTICE": lstat /workspace/META-INF/NOTICE: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/NOTICE.txt": lstat /workspace/META-INF/NOTICE.txt: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/eclipse.inf": lstat /workspace/META-INF/eclipse.inf: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/maven": lstat /workspace/META-INF/maven: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/services": lstat /workspace/META-INF/services: permission denied
[detector]
[detector] failure accessing a path "/workspace/org/apache": lstat /workspace/org/apache: permission denied
[detector]
[detector] failure accessing a path "/workspace/org/eclipse": lstat /workspace/org/eclipse: permission denied
[detector]
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.php-dist@0.0.30
[detector] skip: org.cloudfoundry.php-composer@0.0.16
[detector] pass: org.cloudfoundry.httpd@0.0.21
[detector] fail: org.cloudfoundry.php-web@0.0.24
[detector] ======== Output: org.cloudfoundry.php-composer@0.0.16 ========
[detector] no "composer.json" found in the following locations: [/workspace/composer.json /workspace/htdocs/composer.json]
[detector] ======== Output: org.cloudfoundry.php-web@0.0.24 ========
[detector] failure accessing a path "/workspace/META-INF/DEPENDENCIES": lstat /workspace/META-INF/DEPENDENCIES: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/LICENSE": lstat /workspace/META-INF/LICENSE: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/LICENSE.txt": lstat /workspace/META-INF/LICENSE.txt: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/MANIFEST.MF": lstat /workspace/META-INF/MANIFEST.MF: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/NOTICE": lstat /workspace/META-INF/NOTICE: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/NOTICE.txt": lstat /workspace/META-INF/NOTICE.txt: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/eclipse.inf": lstat /workspace/META-INF/eclipse.inf: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/maven": lstat /workspace/META-INF/maven: permission denied
[detector]
[detector] failure accessing a path "/workspace/META-INF/services": lstat /workspace/META-INF/services: permission denied
[detector]
[detector] failure accessing a path "/workspace/org/apache": lstat /workspace/org/apache: permission denied
[detector]
[detector] failure accessing a path "/workspace/org/eclipse": lstat /workspace/org/eclipse: permission denied
[detector]
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.php-dist@0.0.30
[detector] skip: org.cloudfoundry.php-composer@0.0.16
[detector] pass: org.cloudfoundry.nginx@0.0.25
[detector] fail: org.cloudfoundry.php-web@0.0.24
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.httpd@0.0.21
[detector] Resolving plan... (try #1)
[detector] fail: org.cloudfoundry.httpd@0.0.21 provides unused httpd
[detector] ======== Results ========
[detector] pass: org.cloudfoundry.nginx@0.0.25
[detector] Resolving plan... (try #1)
[detector] fail: org.cloudfoundry.nginx@0.0.25 provides unused nginx
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
ERROR: failed with status code: 6
```

##### Expected

Expected application to be detected properly while generating a valid application image.

---

##### pack info

```
Pack:
  Version:  v0.6.0 (git sha: 109b629d388cec0ed3836b9fed6717727a9187c1)
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.5.0

Config:
  default-builder-image = "some/image"
```

##### docker info

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 87
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: EYY7:72ZD:4GOB:M4FR:ZSPU:5SCA:WLS3:HVWE:R7RM:D42W:IRTY:MAOV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 50
  System Time: 2020-01-22T14:37:01.4525152Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### PR DESCRIPTION
**Pull request by dfreilich**
Some older methods of DOS compression don't contain proper permissions (e.g. `FAT` formatted jars, vs `unix`), and deny buildpacks access to their files. This PR identifies FAT files based on the first byte of their `header.CreaterVersion`, as done in the `zip` source (https://golang.org/src/archive/zip/struct.go). 

Closes #464 

Signed-off-by: David Freilich <dfreilich@vmware.com>

### CODE REVIEW

File: internal/archive/archive.go [hunk 1]
```diff
@@ -257,6 +257,10 @@ func WriteZipToTar(tw *tar.Writer, srcZip, basePath string, uid, gid int, mode i
 			}
 		}
 
+		if overwritePermissions(f.FileHeader) {
```
Comment (zmackie) [inline internal/archive/archive.go:260]: Can this check be done at the top of the loop? Am I understanding it right that *any* `FAT` fileheader would cause the global mode to be overwritten?

File: internal/archive/archive.go [hunk 2]
```diff
@@ -285,6 +289,17 @@ func WriteZipToTar(tw *tar.Writer, srcZip, basePath string, uid, gid int, mode i
...
+	var (
+		creatorFAT  uint16 = 0
+		creatorVFAT uint16 = 14
+	)
+
+	// This identifies FAT files, based on the `zip` source: https://golang.org/src/archive/zip/struct.go
+	firstByte := header.CreatorVersion >> 8
+	return firstByte == creatorFAT || firstByte == creatorVFAT
+}
+
```
Comment (zmackie) [inline internal/archive/archive.go:302]: may we could call this function `isFAT` becaause that's what is does?
or `shouldOverwrite`?

File: internal/archive/archive.go (hunk 1 above)
Comment (dfreilich) [reply internal/archive/archive.go:260]: That is one way of doing it, but we could also do it on a file by file basis, though I'm not sure how much sense that would make.

Comment (zmackie) [reply internal/archive/archive.go]: K yeah I'm not that aware of the internals of handling `FAT`, but I want to be sure that I understand the intention. Let me phrase what this code is doing and you can correct me if I'm wrong:

if we identify a file as `FAT`, we overwrite the `mode` for the entirety of the rest of the function call.

That sound right?

Comment (dfreilich) [reply internal/archive/archive.go]: That is what I'm currently doing. I was opening it up whether I should be doing that, though I would assume that if one file in a zipped dir is a certain format, I should be able to extrapolate that all files are in that format.

Comment (zmackie) [reply internal/archive/archive.go]: Gotcha, yeah that's where my knowledge stops.

File: internal/archive/archive_test.go [hunk 3]
```diff
@@ -302,6 +302,38 @@ func testArchive(t *testing.T, when spec.G, it spec.S) {
 					verify.nextSymLink("/nested/dir/dir-in-archive/sub-dir/link-file", "../some-file.txt")
 				}
 			})
+
+			when.Focus("files are compressed in fat (MSDOS) format", func() {
```
Comment (natalieparellano) [inline internal/archive/archive_test.go:306]: Need to remove this focus :)

File: internal/archive/archive_test.go [hunk 4]
```diff
@@ -302,6 +302,38 @@ func testArchive(t *testing.T, when spec.G, it spec.S) {
...
+					h.AssertNil(t, err)
+					defer file.Close()
+
+					tr := tar.NewReader(file)
+
+					verify := tarVerifier{t, tr, 1234, 2345}
+					// FAT stores names in uppercase: https://superuser.com/a/1297675
+					verify.nextFile("/nested/dir/dir-in-archive/SOME-FIL.TXT", "some-content", 0777)
+					verify.nextDirectory("/nested/dir/dir-in-archive/SUB-DIR", 0777)
+					// FAT doesn't support links: https://unix.stackexchange.com/q/492698
```
Comment (natalieparellano) [inline internal/archive/archive_test.go:332]: I think I understand why this comment is here, at least looking at https://github.com/buildpacks/pack/blob/82549aa7c8980ed7a42b0c8947c0a37d6d1edade/internal/archive/archive_test.go#L118. Given that the fixture FAT wasn't created with a symlink (right?), I wonder if it's necessary? Maybe we don't need to have `LINK-FIL` at all?

File: internal/archive/archive_test.go [hunk 5]
```diff
@@ -302,6 +302,38 @@ func testArchive(t *testing.T, when spec.G, it spec.S) {
...
+					h.AssertNil(t, fh.Close())
+
+					file, err := os.Open(filepath.Join(tmpDir, "some.tar"))
+					h.AssertNil(t, err)
+					defer file.Close()
+
+					tr := tar.NewReader(file)
+
+					verify := tarVerifier{t, tr, 1234, 2345}
+					// FAT stores names in uppercase: https://superuser.com/a/1297675
```
Comment (jromero) [inline internal/archive/archive_test.go:329]: Not sure I'm convinced of this comment based on the contents of the jar in the originating issue (see below). I don't know how the generated file was constructed and maybe the tool used created this artifact but we should remove this comment to prevent unintentionally misinforming people of the contents in all fat formatted zip files.

```
# ORIGINATING FILE
└─▪ zipinfo -m /Users/javier.romero/Downloads/webgoat-container-7.1-exec.jar | head -10
Archive:  /Users/javier.romero/Downloads/webgoat-container-7.1-exec.jar
Zip file size: 74202267 bytes, number of entries: 4239
-rw----     2.0 fat 64791363 bX  0% defN 16-Nov-18 16:51 WebGoat.war
-rw----     2.0 fat   152716 bl 89% defN 16-Nov-18 16:51 conf/web.xml
-rw----     2.0 fat      271 bl 21% defN 16-Nov-18 16:51 tomcat.standalone.properties
-rw----     2.0 fat      638 bl 40% defN 16-Nov-18 16:51 javax/annotation/Generated.class
-rw----     2.0 fat      453 bl 40% defN 16-Nov-18 16:51 javax/annotation/ManagedBean.class
-rw----     2.0 fat      396 bl 40% defN 16-Nov-18 16:51 javax/annotation/PostConstruct.class
-rw----     2.0 fat      390 bl 40% defN 16-Nov-18 16:51 javax/annotation/PreDestroy.class
-rw----     2.0 fat     1179 bl 51% defN 16-Nov-18 16:51 javax/annotation/Resource$AuthenticationType.class


# TEST FILE
└─▪ zipinfo -m ~/Downloads/fat-zip-to-tar.zip
Archive:  /Users/javier.romero/Downloads/fat-zip-to-tar.zip
Zip file size: 502 bytes, number of entries: 3
-rw----     2.0 fat       12 bx  0% stor 20-Apr-21 07:29 SOME-FIL.TXT
drwx---     2.0 fat        0 bx  0% stor 20-Apr-21 07:29 SUB-DIR/
-rw----     2.0 fat       12 bx  0% stor 20-Apr-21 07:29 SUB-DIR/LINK-FIL
3 files, 24 bytes uncompressed, 24 bytes compressed:  0.0%
```

Comment (dfreilich) [reply internal/archive/archive_test.go:329]: You're right, that seems to be something weird when using `zip` on a linux machine. I recreated the dir by zipping it on a windows VM, and it is lower-case

File: internal/archive/archive_test.go (hunk 3 above)
Comment (dfreilich) [reply internal/archive/archive_test.go]: Good point! We should probably add automation to ensure there isn't a Focus...

File: internal/archive/archive_test.go (hunk 4 above)
Comment (dfreilich) [reply internal/archive/archive_test.go:330]: Interesting. I just zipped the dir that is in the testdata, I wanted it to be relatively similar to the `zip-to-tar.zip` file that is in the testdata directory. We can create it without the link-file though

Comment (jromero) [reply internal/archive/archive_test.go:330]: I'm on the fence about this. I see how we got here but in reflection would we intentionally test this if we weren't reusing pre-existing test data. I mean it's good to know but probably not something valuable to test. I'm leaning towards removing it as well. Any strong opposition @dfreilich?

File: internal/archive/archive.go (hunk 1 above)
Comment (jromero) [reply internal/archive/archive.go]: FWIW, I think we're doing the right thing here. A bitwise operation on data we already have present seems like a very small price to pay for the sake of correctness. Each file, could technically, yet not practically, have a different "creator".

File: internal/archive/archive_test.go (hunk 4 above)
Comment (dfreilich) [reply internal/archive/archive_test.go:330]: No, I agree that it's not especially valuable. I'll take it out

File: internal/archive/archive.go (hunk 1 above)
Comment (dfreilich) [reply internal/archive/archive.go]: @jromero Are you arguing in favor of checking/setting the `mode` for every file, or for doing it once for the zipped dir?

Comment (jromero) [reply internal/archive/archive.go]: > checking/setting the mode for every file

Comment (dfreilich) [reply internal/archive/archive.go]: I pushed code that does that - but there's no real way of testing it. Do you still think it makes sense to check file by file?

Comment (jromero) [reply internal/archive/archive.go]: Thanks. I think this is as good as one could wish for. I appreciate the quick change.
