### PR TITLE
Disabling the progress log when downloading files on windows

### LINKED ISSUE #2005: Suddenly LCOW acceptance tests fails with `wsarecv: An existin g connection was forcibly closed by the remote host`
### Summary
 
A few days ago, all the CI workflows started to fail with the error:

```bash
   acceptance_test.go:3166: expected nil: exit status 1: Pulling image 'pack-test/run'                              
 Pulling image 'localhost:59341/pack-test/run'                                                                 
latest: Pulling from pack-test/run                                                                            
Digest: sha256:d0c4072d5e9c1d6921725eef4a7e1a503fa900720d222041d224dc8652a0aefd                               
Status: Image is up to date for localhost:59341/pack-test/run:latest                                          
Pulling image 'pack-test/build'                                                                               
Creating builder 'localhost:59341/test/builder-riiwiwaltt' from build-image 'pack-test/build'                 
Downloading from 'https://github.com/buildpacks/lifecycle/releases/download/v0.17.2/lifecycle-v0.17.2+linux…  
0 B/10.6 MB                                                                                                   
16.4 KB/10.6 MB
ERROR: failed to create builder: fetch lifecycle: downloading lifecycle: writing cache: read tcp 139.178.82.2:51341->185.199.108.133:443: wsarecv: An existing connection was forcibly closed by the remote host.
```
---

##### Steps

1. clone pack repo on a windows machine 
2. run `make acceptance` on windows

##### Current behavior
Acceptance tests on windows (LCOW) fails

##### Expected behavior
Tests should run fine

---

### PR DESCRIPTION
**Pull request by jjbustamante**
## Summary
We added a retry to logic to workaround the error when downloading some files.

#### Before

Acceptance tests on windows (LCOW) were failing 

#### After

Acceptance test are passing

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #2005

### CODE REVIEW

File: pkg/blob/downloader.go [hunk 1]
```diff
@@ -57,6 +57,10 @@ func (d *downloader) Download(ctx context.Context, pathOrURI string) (Blob, erro
 			path, err = paths.URIToFilePath(pathOrURI)
 		case "http", "https":
 			path, err = d.handleHTTP(ctx, pathOrURI)
+			if err != nil {
+				// retry
```
Comment (natalieparellano) [inline pkg/blob/downloader.go:61]:
```suggestion
				// retry as we sometimes see `wsarecv: An existing connection was forcibly closed by the remote host.` on Windows
```

Comment (natalieparellano) [reply pkg/blob/downloader.go:61]: It's too bad we don't have greater insight into why this happens - but this seems sensible for now

**Review by natalieparellano — APPROVED** [review]
