### PR TITLE
Fix registry selector flag in build command and validation for the input

### LINKED ISSUE #747: Update `pack build -R` to use named buildpack registries
### Description

As a pack user, I would like to use a **named registry* when running `build`. Currently the `-R` flag takes a git URL. This flag should also be aligned with `pack register-builderpack -r` (notice the lowercase `-r`).

### Proposed solution

1. Change the casing of `-R` flag to `-r`
2. `-r` should accept ONLY a named registry instead of a git URL

### Additional context
- [ ] This feature should be documented somewhere

### PR DESCRIPTION
**Pull request by supra08**
Signed-off-by: Supratik Das <rick.das08@gmail.com>

## Summary
This PR attempts to fix #747. It replaces the `-R` flag for selecting the registry in `pack build` to `-r`. It also puts a validation for rejecting git/https based URLs. 

## Documentation

- Should this change be documented?
    - [x] Yes, see #___
    - [ ] No

## Related

Resolves #747

### CODE REVIEW

**Review by dfreilich — CHANGES_REQUESTED** [review]
Thanks for the additions! Would you be able to add tests, verifying that the regex works as expected?

File: build.go [hunk 1]
```diff
@@ -646,6 +647,11 @@ func (c *Client) processBuildpacks(ctx context.Context, builderImage imgutil.Ima
 			fetchedBPs = append(append(fetchedBPs, mainBP), depBPs...)
 			order = appendBuildpackToOrder(order, mainBP.Descriptor().Info)
 		case buildpack.RegistryLocator:
+			r := regexp.MustCompile(`^(https|git)(://|@)([^/:]+)[/:]([^/:]+)/(.+).git$`)
+			if r.MatchString(registry) {
+				return fetchedBPs, order, errors.New("registry should be only specified as named")
+			}
+
 			registryCache, err := c.getRegistry(c.logger, registry)
```
Comment (jromero) [inline build.go:655]: There may be some confusion on the original requirements. The flag should no longer accept a URI at all and instead only support **name**s from the `config.toml` files.

This is taken from the [latest PR changes](https://github.com/buildpacks/pack/pull/716#issue-441624401):

> By default, if no configuration values are defined in the `config.toml` file, buildpacks will be registered against:
> `https://github.com/buildpacks/registry`. In addition, user can specify their own registries. For example:
> 
> ```
> [[registries]]
> name="elbandito"
> type="github"
> url="https://github.com/elbandito/buildpack-registry"
> 
> [[registries]]
> name="joe"
> type="github"
> url="https://github.com/jkutner/buildpack-registry/"
> ```
> 
> When there are multiple `registries`, the user can specify a specific registry via `buildpack-registry, -R` flag.
> 
> For example:
> `pack register-buildpack <buildpack/image> -r elbandito`

- See also https://github.com/buildpacks/pack/issues/745

A possible solution may be to change `c.getRegistry` to accept a "name" and then it can then look up the URL from the `config.toml` instead of it being passed in.

File: internal/commands/build.go [hunk 2]
```diff
@@ -144,7 +144,7 @@ func Build(logger logging.Logger, cfg config.Config, packClient PackClient) *cob
 func buildCommandFlags(cmd *cobra.Command, buildFlags *BuildFlags, cfg config.Config) {
 	cmd.Flags().StringVarP(&buildFlags.AppPath, "path", "p", "", "Path to app dir or zip-formatted file (defaults to current working directory)")
 	cmd.Flags().StringVarP(&buildFlags.Builder, "builder", "B", cfg.DefaultBuilder, "Builder image")
-	cmd.Flags().StringVarP(&buildFlags.Registry, "buildpack-registry", "R", cfg.DefaultRegistry, "Buildpack Registry URL")
+	cmd.Flags().StringVarP(&buildFlags.Registry, "buildpack-registry", "r", cfg.DefaultRegistry, "Buildpack Registry URL")
```
Comment (jromero) [inline internal/commands/build.go:147]:
```suggestion
	cmd.Flags().StringVarP(&buildFlags.Registry, "buildpack-registry", "r", cfg.DefaultRegistry, "Buildpack registry by name")
```

**Review by jromero — CHANGES_REQUESTED** [review]

**Comment by jromero** [comment]
Hi @supra08, just checking in. Is there anything I can clarify or you need from me/us?

**Comment by supra08** [comment]
Oh hi @jromero, no there is nothing as of now. I was stuck with some university formalities so the delay. It will be good to go in a couple of days.

File: internal/commands/build.go (hunk 2 above)
Comment (elbandito) [reply internal/commands/build.go]: @supra08 FYI, `cfg.DefaultRegistry` has been deprecated.   This should be `cfg.DefaultRegistryName`.  This is also why some of your Unit Tests are failing.

**Comment by supra08** [comment]
One of the unit tests is failing, working on it.

**Comment by jromero** [comment]
### ✔️  Accepted

_NOTE: Errors are expected since no publically accessible image is available on the registry yet._

```
$ cat ~/.pack/config.toml
default-registry = "official"
experimental = true

[[registries]]
  name = "my-registry-1"
  type = "github"
  url = "https://example.com/1"

[[registries]]
  name = "my-registry-2"
  type = "github"
  url = "https://example.com/2"

[[registries]]
  name = "a-registry-1"
  type = "github"
  url = "https://example.com/1"

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b test/node-function
...
Status: Downloaded newer image for heroku/pack:18
ERROR: failed to build: creating from buildpackage test/node-function: fetching image: image test/node-function does not exist on the daemon: not found

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b test/node-function@0.6.2
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: invalid buildpack string test/node-function@0.6.2

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b urn:cnb:registry:test/node-function@0.6.2
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: extracting from registry urn:cnb:registry:test/node-function@0.6.2: fetching image: connect to repo store 'gcr.io/test/node-function@sha256:9d88250dfd77dbf5a535f1358c6a05dc2c0d3a22defbdcd72bb8f5e24b84e21d': GET https://gcr.io/v2/token?scope=repository%3Atest%2Fnode-function%3Apull&service=gcr.io: UNKNOWN: Project 'project:test' not found or deleted.

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b urn:cnb:registry:test/node-function
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: extracting from registry urn:cnb:registry:test/node-function: fetching image: connect to repo store 'gcr.io/test/node-function@sha256:9d88250dfd77dbf5a535f1358c6a05dc2c0d3a22defbdcd72bb8f5e24b84e21d': GET https://gcr.io/v2/token?scope=repository%3Atest%2Fnode-function%3Apull&service=gcr.io: UNKNOWN: Project 'project:test' not found or deleted.

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b urn:cnb:registry:test/node-function -r my-registry-1
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: locating in registry urn:cnb:registry:test/node-function: refreshing cache: initializing (/Users/javier.romero/.pack/registry-f2f9784142e4d11e32b550593e53fa187718c7c3435936d7845bf0300d28391c): creating registry cache: cloning remote registry: repository not found

$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b urn:cnb:registry:test/node-function -r unset-registry
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: invalid registry 'unset-registry': registry unset-registry is not defined in your config file

$ vim ~/.pack/config.toml
$ cat ~/.pack/config.toml
default-registry = "my-registry-1"
experimental = true

[[registries]]
  name = "my-registry-1"
  type = "github"
  url = "https://example.com/1"

[[registries]]
  name = "my-registry-2"
  type = "github"
  url = "https://example.com/2"

[[registries]]
  name = "a-registry-1"
  type = "github"
  url = "https://example.com/1"


$ ./out/pack build my-app -p ../samples/apps/bash-script/ -B heroku/buildpacks:18 -b urn:cnb:registry:test/node-function
...
Status: Image is up to date for heroku/pack:18
ERROR: failed to build: locating in registry urn:cnb:registry:test/node-function: refreshing cache: initializing (/Users/javier.romero/.pack/registry-f2f9784142e4d11e32b550593e53fa187718c7c3435936d7845bf0300d28391c): creating registry cache: cloning remote registry: repository not found
```

**Comment by jromero** [comment]
NOTE: Documentation deferred until the buildpacks registry workflow is more complete.

**Comment by jromero** [comment]
A huge thanks @supra08! 👏 👏 👏  Thank you for putting in the work and coordinating with us in order to be able to :ship: this today.

**Comment by elbandito** [comment]
Good job getting this over the finish line @supra08! 🥳
