### PR TITLE
Warn if project.toml contains keys not supported by schema

### LINKED ISSUE #1922: Pack silently fails to use `project.toml` if the `schema-version` is not specified
### Summary
If a `project.toml` file does not contain an appropriately set `schema-version`, Pack silently ignores values set in the `project.toml` file, leading to a frustrating to debug experience.

---

##### Steps

1. `mkdir testcase && cd $_ `
2. `echo -e "[io.buildpacks]\nbuilder = \"some-builder\"" > project.toml`
3. `pack build testcase`

##### Current behavior

The `pack build` tries to perform a build using whatever is set as the default builder.

The cause of this is that the `builder` property is only supported as of `project.toml` schema version 0.2, but Pack CLI silently defaults to v0.1 if no schema version was specified, and ignores knowns keys rather than failing with a schema validation error.

If I add this, then the expected behaviour occurs:

```
[_]
schema-version = "0.2"
```

##### Expected behavior

For either:
1. Pack to default The build to be performed using the specified builder (which would fail with an invalid builder error, but this is just a testcase)
2. Pack to output a warning or error saying "no `schema-version` specified, defaulting to schema v0.1", along with perhaps a schema v0.1 validation error about the `builder` property not being recognised.

---

##### pack info

```
$ pack report
Pack:
  Version:  0.31.0+git-3a994bd.build-5086
  OS/Arch:  darwin/arm64

Default Lifecycle Version:  0.17.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12

Config:
  default-builder-image = "[REDACTED]"
  experimental = true
  
  [[trusted-builders]]
    name = "[REDACTED]"
  
  [[trusted-builders]]
    name = "[REDACTED]"
```

### PR DESCRIPTION
**Pull request by colincasey**
## Summary

As detailed in #1922, a common source of confusion with `project.toml` is failing to declare the `schema-version`. The `schema-version` then silently defaults to `0.1` which can lead to confusing and hard to debug errors when the user is using keys from the `0.2` schema.

This PR adds messaging to the build output notifying the user if:
- the schema version defaults to `0.1`
- the project descriptor contains unsupported keys for the target schema version and these keys will be ignored

#### Before

```
Using project descriptor located at '/var/folders/r4/xq3q_hjj2v1ghqlnr1k1zrdw0000gp/T/unsupported-schema-keys-app2010798657/project.toml'
Builder 'localhost:55020/test/builder-meaprzkkef' is trusted
Warning: Ignoring the provided lifecycle image as the builder is trusted, running the creator in a single container using the provided builder
Pulling image 'localhost:55020/test/builder-meaprzkkef:latest'
latest: Pulling from test/builder-meaprzkkef
Digest: sha256:b23b53c8d15aefb31136b9c2cda830a62a801bfb3fad413c3496a775c3ca9bc1
Status: Image is up to date for localhost:55020/test/builder-meaprzkkef:latest
CheckReadAccess failed for the run image pack-test/run, error: HEAD https://index.docker.io/v2/pack-test/run/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
CheckReadAccess succeeded for the run image localhost:55020/pack-test/run
Selected run image mirror 'localhost:55020/pack-test/run'
Pulling image 'localhost:55020/pack-test/run'
latest: Pulling from pack-test/run
Digest: sha256:39b229916f00ebfd4e824e7d55f55d31679ab856f0ce6590ab156c85088f09f8
Status: Image is up to date for localhost:55020/pack-test/run:latest
Creating builder with the following buildpacks:
-> 'read/env@read-env-version'
-> 'noop.buildpack@noop.buildpack.version'
-> 'noop.buildpack@noop.buildpack.later-version'
-> 'simple/layers@simple-layers-version'
Using build cache volume 'pack-cache-some-org_yrjscyouuj_latest-82c320b56cc2.build'
Running the 'creator' on OS 'linux' from image 'pack.local/builder/616d78677a73746b7975:latest' with:
Container Settings:
  Args: '/cnb/lifecycle/creator -daemon -launch-cache /launch-cache -log-level debug -app /workspace -cache-dir /cache -run-image localhost:55020/pack-test/run localhost:55020/some-org/yrjscyouuj'
  System Envs: 'CNB_PLATFORM_API=0.12'
  Image: 'pack.local/builder/616d78677a73746b7975:latest'
  User: 'root'
  Labels: 'map[author:pack]'
Host Settings:
  Binds: 'pack-cache-some-org_yrjscyouuj_latest-82c320b56cc2.build:/cache /var/run/docker.sock:/var/run/docker.sock pack-cache-some-org_yrjscyouuj_latest-82c320b56cc2.launch:/launch-cache pack-layers-gpqabucfga:/layers pack-app-zzbdnhrczc:/workspace'
  Network Mode: ''
Starting creator...
Parsing inputs...
Ensuring privileges...
Executing command...
===> ANALYZING
Timer: Analyzer started at 2024-01-30T15:57:26Z
Image with name "localhost:55020/some-org/yrjscyouuj" not found
Found image with identifier "0fd546a7ba0d7372c867c5e481935bf45fab514ed73ed65574c23010b4014b3a"
Timer: Analyzer ran for 89.712µs and ended at 2024-01-30T15:57:26Z
Run image info in analyzed metadata is: 
{"Reference":"0fd546a7ba0d7372c867c5e481935bf45fab514ed73ed65574c23010b4014b3a","Image":"localhost:55020/pack-test/run","Extend":false,"target":{"os":"linux","arch":"amd64"}}
===> DETECTING
Timer: Detector started at 2024-01-30T15:57:26Z
Checking for match against descriptor: {windows   []}
Checking for match against descriptor: {linux   []}
Checking for match against descriptor: {windows   []}
Checking for match against descriptor: {linux   []}
======== Output: read/env@read-env-version ========
---> DETECT: Printenv buildpack
======== Results ========
pass: simple/layers@simple-layers-version
err:  read/env@read-env-version (1)
Resolving plan... (try #1)
1 of 2 buildpacks participating
simple/layers simple-layers-version
Timer: Detector ran for 3.066373ms and ended at 2024-01-30T15:57:26Z
===> RESTORING
Timer: Restorer started at 2024-01-30T15:57:26Z
Restoring Layer Metadata
Reading buildpack directory: /layers/simple_layers
Reading Buildpack Layers directory /layers
Reading buildpack directory: /layers/simple_layers
Timer: Restorer ran for 216.031µs and ended at 2024-01-30T15:57:26Z
===> BUILDING
Timer: Builder started at 2024-01-30T15:57:26Z
Running build for buildpack simple/layers@simple-layers-version
Looking up buildpack
Finding plan
Creating plan directory
Preparing paths
Running build command
---> Build: Simple Layers Buildpack
making launch layer
Color: Styled
making cached launch layer
---> Done
Processing layers
Updating environment
Reading output files
Updating buildpack processes
Updating process list
Finished running build for buildpack simple/layers@simple-layers-version
Copying SBOM files
Creating SBOM files for legacy BOM
Listing processes
Timer: Builder ran for 7.72566ms and ended at 2024-01-30T15:57:26Z
===> EXPORTING
Timer: Exporter started at 2024-01-30T15:57:26Z
Copying SBOM lifecycle.sbom.cdx.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.cdx.json
Copying SBOM lifecycle.sbom.spdx.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.spdx.json
Copying SBOM lifecycle.sbom.syft.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.syft.json
Copying SBOM launcher.sbom.cdx.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.cdx.json
Copying SBOM launcher.sbom.spdx.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.spdx.json
Copying SBOM launcher.sbom.syft.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.syft.json
Reading buildpack directory: /layers/simple_layers
Reading buildpack directory item: cached-launch-layer
Reading buildpack directory item: cached-launch-layer.toml
Reading buildpack directory item: launch-layer
Reading buildpack directory item: launch-layer.toml
Reading buildpack directory item: launch.toml
Processing buildpack directory: /layers/simple_layers
Processing launch layer: /layers/simple_layers/cached-launch-layer
Reusing tarball for layer "simple/layers:cached-launch-layer" with SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Adding layer 'simple/layers:cached-launch-layer'
Layer 'simple/layers:cached-launch-layer' SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Processing launch layer: /layers/simple_layers/launch-layer
Reusing tarball for layer "simple/layers:launch-layer" with SHA: sha256:c7c0f2d747d3a9c4908676a95162751870928838385c678252d009c0e9dcbf8d
Adding layer 'simple/layers:launch-layer'
Layer 'simple/layers:launch-layer' SHA: sha256:c7c0f2d747d3a9c4908676a95162751870928838385c678252d009c0e9dcbf8d
Found SBOM of type launch for at /layers/sbom/launch
Reusing tarball for layer "buildpacksio/lifecycle:launch.sbom" with SHA: sha256:f04b500e5e9718eb5f2e88a2f45b379c54582cceb4d45fd646ae4fd667544833
Adding layer 'buildpacksio/lifecycle:launch.sbom'
Layer 'buildpacksio/lifecycle:launch.sbom' SHA: sha256:f04b500e5e9718eb5f2e88a2f45b379c54582cceb4d45fd646ae4fd667544833
Layer 'slice-1' SHA: sha256:56485c63acd23a4bb4c2126a7ccd5f7a64eb4294363d37b2c38a3d440a91877f
Adding 1/1 app layer(s)
Reusing tarball for layer "buildpacksio/lifecycle:launcher" with SHA: sha256:99546a12b358b8416518f8f76b3ef3b6488dea026b1d6e7528e0c81a140e364c
Adding layer 'buildpacksio/lifecycle:launcher'
Layer 'buildpacksio/lifecycle:launcher' SHA: sha256:99546a12b358b8416518f8f76b3ef3b6488dea026b1d6e7528e0c81a140e364c
Reusing tarball for layer "buildpacksio/lifecycle:config" with SHA: sha256:500dce5089145ac4c359c37c209e91d0a54b20db0f6196b78c0b366bbd529af2
Adding layer 'buildpacksio/lifecycle:config'
Layer 'buildpacksio/lifecycle:config' SHA: sha256:500dce5089145ac4c359c37c209e91d0a54b20db0f6196b78c0b366bbd529af2
Reusing tarball for layer "buildpacksio/lifecycle:process-types" with SHA: sha256:af8140367e05484cbc8b071fa4405dc0f2c8d72047eeef495d1c73794a31aaa8
Adding layer 'buildpacksio/lifecycle:process-types'
Layer 'buildpacksio/lifecycle:process-types' SHA: sha256:af8140367e05484cbc8b071fa4405dc0f2c8d72047eeef495d1c73794a31aaa8
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting CNB_LAYERS_DIR=/layers
Setting CNB_APP_DIR=/workspace
Setting CNB_PLATFORM_API=0.12
Setting CNB_DEPRECATION_MODE=quiet
Prepending /cnb/process and /cnb/lifecycle to PATH
Setting WORKDIR: '/workspace'
Setting default process type 'web'
Setting ENTRYPOINT: '/cnb/process/web'
Timer: Saving localhost:55020/some-org/yrjscyouuj... started at 2024-01-30T15:57:26Z
Saving localhost:55020/some-org/yrjscyouuj...
*** Images (c410a9758de7):
      localhost:55020/some-org/yrjscyouuj

*** Image ID: c410a9758de7b42452be22acc8885f09c0a4ac7ee8b50a9c254b784422d0e96a
Timer: Saving localhost:55020/some-org/yrjscyouuj... ran for 98.867761ms and ended at 2024-01-30T15:57:26Z
Timer: Exporter ran for 114.362919ms and ended at 2024-01-30T15:57:26Z
Timer: Cache started at 2024-01-30T15:57:26Z
Reading buildpack directory: /layers/simple_layers
Reading buildpack directory item: cached-launch-layer
Reading buildpack directory item: cached-launch-layer.toml
Reading buildpack directory item: launch-layer
Reading buildpack directory item: launch-layer.toml
Reading buildpack directory item: launch.toml
Reusing tarball for layer "simple/layers:cached-launch-layer" with SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Adding cache layer 'simple/layers:cached-launch-layer'
Layer 'simple/layers:cached-launch-layer' SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Timer: Cache ran for 415.234µs and ended at 2024-01-30T15:57:26Z
Successfully built image 'localhost:55020/some-org/yrjscyouuj'
```

#### After

```
Warning: No schema version declared in project.toml, defaulting to schema version 0.1
Warning: The following keys declared in project.toml are not supported in schema version 0.1:
Warning: - unsupported-table
Warning: - unsupported-table.unsupported-key
Warning: The above keys will be ignored. If this is not intentional, maybe try updating your schema version.
Using project descriptor located at '/var/folders/r4/xq3q_hjj2v1ghqlnr1k1zrdw0000gp/T/unsupported-schema-keys-app3484545732/project.toml'
Builder 'localhost:55019/test/builder-jsxduvkchu' is trusted
Warning: Ignoring the provided lifecycle image as the builder is trusted, running the creator in a single container using the provided builder
Pulling image 'localhost:55019/test/builder-jsxduvkchu:latest'
latest: Pulling from test/builder-jsxduvkchu
Digest: sha256:7cbf27f1aab214ce606fdfc0e2b2893556a87d236f28b4031ec0be4887077fc4
Status: Image is up to date for localhost:55019/test/builder-jsxduvkchu:latest
CheckReadAccess failed for the run image pack-test/run, error: HEAD https://index.docker.io/v2/pack-test/run/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
CheckReadAccess succeeded for the run image localhost:55019/pack-test/run
Selected run image mirror 'localhost:55019/pack-test/run'
Pulling image 'localhost:55019/pack-test/run'
latest: Pulling from pack-test/run
Digest: sha256:b50b903bd1bc071b62c51245fc3370b5395ee491a243d187957328ef09fe7dd7
Status: Image is up to date for localhost:55019/pack-test/run:latest
Creating builder with the following buildpacks:
-> 'read/env@read-env-version'
-> 'noop.buildpack@noop.buildpack.version'
-> 'noop.buildpack@noop.buildpack.later-version'
-> 'simple/layers@simple-layers-version'
Using build cache volume 'pack-cache-some-org_kfwylzvwwb_latest-cfa683507d8c.build'
Running the 'creator' on OS 'linux' from image 'pack.local/builder/72616369697a6c666d70:latest' with:
Container Settings:
  Args: '/cnb/lifecycle/creator -daemon -launch-cache /launch-cache -log-level debug -app /workspace -cache-dir /cache -run-image localhost:55019/pack-test/run localhost:55019/some-org/kfwylzvwwb'
  System Envs: 'CNB_PLATFORM_API=0.12'
  Image: 'pack.local/builder/72616369697a6c666d70:latest'
  User: 'root'
  Labels: 'map[author:pack]'
Host Settings:
  Binds: 'pack-cache-some-org_kfwylzvwwb_latest-cfa683507d8c.build:/cache /var/run/docker.sock:/var/run/docker.sock pack-cache-some-org_kfwylzvwwb_latest-cfa683507d8c.launch:/launch-cache pack-layers-ozsnlglowg:/layers pack-app-oimwptfqrk:/workspace'
  Network Mode: ''
Starting creator...
Parsing inputs...
Ensuring privileges...
Executing command...
===> ANALYZING
Timer: Analyzer started at 2024-01-30T15:51:05Z
Image with name "localhost:55019/some-org/kfwylzvwwb" not found
Found image with identifier "26aa2577d4ca6bc9484aabea2f11aa98f77af7ca62ef7641e706650d8b7fd85f"
Timer: Analyzer ran for 40.04µs and ended at 2024-01-30T15:51:05Z
Run image info in analyzed metadata is: 
{"Reference":"26aa2577d4ca6bc9484aabea2f11aa98f77af7ca62ef7641e706650d8b7fd85f","Image":"localhost:55019/pack-test/run","Extend":false,"target":{"os":"linux","arch":"amd64"}}
===> DETECTING
Timer: Detector started at 2024-01-30T15:51:05Z
Checking for match against descriptor: {windows   []}
Checking for match against descriptor: {linux   []}
Checking for match against descriptor: {windows   []}
Checking for match against descriptor: {linux   []}
======== Output: read/env@read-env-version ========
---> DETECT: Printenv buildpack
======== Results ========
pass: simple/layers@simple-layers-version
err:  read/env@read-env-version (1)
Resolving plan... (try #1)
1 of 2 buildpacks participating
simple/layers simple-layers-version
Timer: Detector ran for 3.30326ms and ended at 2024-01-30T15:51:05Z
===> RESTORING
Timer: Restorer started at 2024-01-30T15:51:05Z
Restoring Layer Metadata
Reading buildpack directory: /layers/simple_layers
Reading Buildpack Layers directory /layers
Reading buildpack directory: /layers/simple_layers
Timer: Restorer ran for 148.084µs and ended at 2024-01-30T15:51:05Z
===> BUILDING
Timer: Builder started at 2024-01-30T15:51:05Z
Running build for buildpack simple/layers@simple-layers-version
Looking up buildpack
Finding plan
Creating plan directory
Preparing paths
Running build command
---> Build: Simple Layers Buildpack
making launch layer
Color: Styled
making cached launch layer
---> Done
Processing layers
Updating environment
Reading output files
Updating buildpack processes
Updating process list
Finished running build for buildpack simple/layers@simple-layers-version
Copying SBOM files
Creating SBOM files for legacy BOM
Listing processes
Timer: Builder ran for 8.209206ms and ended at 2024-01-30T15:51:05Z
===> EXPORTING
Timer: Exporter started at 2024-01-30T15:51:05Z
Copying SBOM lifecycle.sbom.cdx.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.cdx.json
Copying SBOM lifecycle.sbom.spdx.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.spdx.json
Copying SBOM lifecycle.sbom.syft.json to /layers/sbom/build/buildpacksio_lifecycle/sbom.syft.json
Copying SBOM launcher.sbom.cdx.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.cdx.json
Copying SBOM launcher.sbom.spdx.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.spdx.json
Copying SBOM launcher.sbom.syft.json to /layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.syft.json
Reading buildpack directory: /layers/simple_layers
Reading buildpack directory item: cached-launch-layer
Reading buildpack directory item: cached-launch-layer.toml
Reading buildpack directory item: launch-layer
Reading buildpack directory item: launch-layer.toml
Reading buildpack directory item: launch.toml
Processing buildpack directory: /layers/simple_layers
Processing launch layer: /layers/simple_layers/cached-launch-layer
Reusing tarball for layer "simple/layers:cached-launch-layer" with SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Adding layer 'simple/layers:cached-launch-layer'
Layer 'simple/layers:cached-launch-layer' SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Processing launch layer: /layers/simple_layers/launch-layer
Reusing tarball for layer "simple/layers:launch-layer" with SHA: sha256:c7c0f2d747d3a9c4908676a95162751870928838385c678252d009c0e9dcbf8d
Adding layer 'simple/layers:launch-layer'
Layer 'simple/layers:launch-layer' SHA: sha256:c7c0f2d747d3a9c4908676a95162751870928838385c678252d009c0e9dcbf8d
Found SBOM of type launch for at /layers/sbom/launch
Reusing tarball for layer "buildpacksio/lifecycle:launch.sbom" with SHA: sha256:f04b500e5e9718eb5f2e88a2f45b379c54582cceb4d45fd646ae4fd667544833
Adding layer 'buildpacksio/lifecycle:launch.sbom'
Layer 'buildpacksio/lifecycle:launch.sbom' SHA: sha256:f04b500e5e9718eb5f2e88a2f45b379c54582cceb4d45fd646ae4fd667544833
Layer 'slice-1' SHA: sha256:11463a1d7b4e218b8bb1ecdbb12f5db3bdfc59fd7c4110222d3279aedb2d2590
Adding 1/1 app layer(s)
Reusing tarball for layer "buildpacksio/lifecycle:launcher" with SHA: sha256:99546a12b358b8416518f8f76b3ef3b6488dea026b1d6e7528e0c81a140e364c
Adding layer 'buildpacksio/lifecycle:launcher'
Layer 'buildpacksio/lifecycle:launcher' SHA: sha256:99546a12b358b8416518f8f76b3ef3b6488dea026b1d6e7528e0c81a140e364c
Reusing tarball for layer "buildpacksio/lifecycle:config" with SHA: sha256:500dce5089145ac4c359c37c209e91d0a54b20db0f6196b78c0b366bbd529af2
Adding layer 'buildpacksio/lifecycle:config'
Layer 'buildpacksio/lifecycle:config' SHA: sha256:500dce5089145ac4c359c37c209e91d0a54b20db0f6196b78c0b366bbd529af2
Reusing tarball for layer "buildpacksio/lifecycle:process-types" with SHA: sha256:af8140367e05484cbc8b071fa4405dc0f2c8d72047eeef495d1c73794a31aaa8
Adding layer 'buildpacksio/lifecycle:process-types'
Layer 'buildpacksio/lifecycle:process-types' SHA: sha256:af8140367e05484cbc8b071fa4405dc0f2c8d72047eeef495d1c73794a31aaa8
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting CNB_LAYERS_DIR=/layers
Setting CNB_APP_DIR=/workspace
Setting CNB_PLATFORM_API=0.12
Setting CNB_DEPRECATION_MODE=quiet
Prepending /cnb/process and /cnb/lifecycle to PATH
Setting WORKDIR: '/workspace'
Setting default process type 'web'
Setting ENTRYPOINT: '/cnb/process/web'
Timer: Saving localhost:55019/some-org/kfwylzvwwb... started at 2024-01-30T15:51:05Z
Saving localhost:55019/some-org/kfwylzvwwb...
*** Images (1966546be8b9):
      localhost:55019/some-org/kfwylzvwwb

*** Image ID: 1966546be8b9dcb294a1076a457a57bf7bb3aa73904fd666f581213281336306
Timer: Saving localhost:55019/some-org/kfwylzvwwb... ran for 144.726225ms and ended at 2024-01-30T15:51:05Z
Timer: Exporter ran for 166.904572ms and ended at 2024-01-30T15:51:05Z
Timer: Cache started at 2024-01-30T15:51:05Z
Reading buildpack directory: /layers/simple_layers
Reading buildpack directory item: cached-launch-layer
Reading buildpack directory item: cached-launch-layer.toml
Reading buildpack directory item: launch-layer
Reading buildpack directory item: launch-layer.toml
Reading buildpack directory item: launch.toml
Reusing tarball for layer "simple/layers:cached-launch-layer" with SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Adding cache layer 'simple/layers:cached-launch-layer'
Layer 'simple/layers:cached-launch-layer' SHA: sha256:86da3c03587957e4e7571259d7cefb913e991ddb19164862f40159362b78f3a0
Timer: Cache ran for 375.724µs and ended at 2024-01-30T15:51:05Z
Successfully built image 'localhost:55019/some-org/kfwylzvwwb'
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1922

### CODE REVIEW

File: pkg/project/project.go [hunk 1]
```diff
@@ -45,21 +46,44 @@ func ReadProjectDescriptor(pathToFile string) (types.Descriptor, error) {
 
 	version := versionDescriptor.Project.Version
 	if version == "" {
+		fmt.Println("No schema version declared in project.toml, defaulting to schema version 0.1")
```
Comment (edmorley) [inline pkg/project/project.go:49]: The spec states that the file must contain a schema version:
https://github.com/buildpacks/pack/issues/1922#issuecomment-1737632210

As such, perhaps we should make this an error instead of a warning?

**Comment by edmorley** [comment]
Thank you for implementing this! It's caught several people out (myself included), so looking forward to the better UX here :-)

File: pkg/project/project.go (hunk 1 above)
Comment (colincasey) [reply pkg/project/project.go:49]: @edmorley not if you go back far enough in the history (like [here](https://github.com/buildpacks/spec/blob/981e9f8b2daa2f6b219f0431edc03881dc61a78d/extensions/project-descriptor.md)). it seems like the spec only started mandating a schema version starting with the `0.2` project descriptor.  

if we allow for no schema version for backwards compatibility with the `0.1` format then you end up with this PR. i also have a version that enforces the schema version for the `0.1` format too but those changes would not be backwards compatible. 

@hone i noticed that the first appearance of the "MUST contain a schema version" text was in [this commit](https://github.com/buildpacks/spec/commit/9f1e939cfed0c64175bdcf782600201d417d7ac0) from you.  can you clarify if this restriction should apply only to the `0.2` format or both `0.2` and `0.1`?

File: pkg/project/project.go [hunk 2]
```diff
@@ -4,6 +4,7 @@ import (
 	"fmt"
 	"os"
 	"path/filepath"
+	"strings"
```
Comment (jjbustamante) [inline pkg/project/project.go:7]: Is it possible to passthrough the **logging.Logger** instance from:

- `internal/commands/build.go` to `func parseProjectToml(appPath, descriptorPath string)` and finally to `func ReadProjectDescriptor(pathToFile string)` in that way we don't need to use `fmt`
 

func ReadProjectDescriptor(pathToFile string) (types.Descriptor, error)

**Review by jjbustamante — CHANGES_REQUESTED** [review]
Thanks a lot for this PR @colincasey, just a quick suggestion with the use of `fmt`

File: pkg/project/project.go (hunk 1 above)
Comment (jjbustamante) [reply pkg/project/project.go:49]: I agreed with @colincasey, I think one strategy could be:
1. We keep for now defaulting to 0.1 schema if no schema is present
2. At some point, we will deprecate 0.1 and maybe this message could be updated to inform the user they MUST declare the schema version, because support for 0.1 will be remove on pack X.Y.Z version
3. Once we deprecate support for 0.1 in pack X.Y.Z then we can fail the build

File: pkg/project/project.go (hunk 2 above)
Comment (colincasey) [reply pkg/project/project.go:7]: @jjbustamante thanks for that suggestion. By passing through the logger I was able to drop the more expensive acceptance tests and replace them with equivalent unit tests.

**Review by jjbustamante — APPROVED** [review]
Thank you @colincasey
