### PR TITLE
Make the `pack build` warn that the positional argument will not be treated as the source directory path

### LINKED ISSUE #2231: UX bug, warn when using the image name the same as a local directory
### Summary

If you run this:

```
$ pack build ./ruby-getting-started
```

It will try to build an image named "./ruby-getting-started" instead of building an image with the contents of the directory in `./ruby-getting-started`

##### Steps

```
$ git clone https://github.com/heroku/ruby-getting-started
$ pack config default-builder heroku/builder:24
$ pack build ./ruby-getting-started
```

##### Current behavior

```
$ pack build ./ruby-getting-started
24: Pulling from heroku/builder
c3c95e61d135: Already exists
51d8f1b9713f: Pull complete
5a2ba7ce94a1: Pull complete
182afb1fe5dc: Pull complete
a6d1c250c7ea: Pull complete
871d0c542f96: Pull complete
bb2d5bbfa209: Pull complete
1a22f95c2361: Pull complete
35c3a9574722: Pull complete
99677fb6a9c6: Pull complete
cc63f855e080: Pull complete
81491acfe764: Pull complete
113fe7e3e540: Pull complete
9822e4b97eba: Pull complete
ba2d82eef5c3: Pull complete
f48aa984467d: Pull complete
ffaf58b86fd8: Pull complete
6343107da9e3: Pull complete
a4fea99767cd: Pull complete
f63217451a36: Pull complete
15ee3b84c724: Pull complete
3a4558bbdea5: Pull complete
08b352b17a85: Pull complete
4fb627380bfa: Pull complete
962feb4a90d7: Pull complete
183b762aa2b7: Pull complete
0814ee8e7dab: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:96bc5b2df323bdd8349fae20bc716c6c471ea6cdaad361ad2d7941bd2f10557f
Status: Downloaded newer image for heroku/builder:24
24: Pulling from heroku/heroku
eed1663d2238: Already exists
51d8f1b9713f: Already exists
Digest: sha256:36e92b6b4e2a980a02363b9f1ddce582c32f38e236b778a6570dedf3d52ab733
Status: Downloaded newer image for heroku/heroku:24
===> ANALYZING
Image with name "./ruby-getting-started" not found
===> DETECTING
======== Output: heroku/python@0.12.1 ========
No Python project files found (such as requirements.txt).
======== Results ========
fail: heroku/python@0.12.1
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/nodejs-engine@3.2.8
skip: heroku/nodejs-yarn@3.2.8
pass: heroku/jvm@6.0.1
pass: heroku/ruby@3.0.0
skip: heroku/procfile@3.1.2
Resolving plan... (try #1)
fail: heroku/nodejs-engine@3.2.8 provides unused node
Resolving plan... (try #2)
skip: heroku/nodejs-engine@3.2.8 provides unused node
skip: heroku/jvm@6.0.1 provides unused jdk
fail: heroku/ruby@3.0.0 provides unused ruby
======== Results ========
pass: heroku/nodejs-engine@3.2.8
fail: heroku/nodejs-corepack@3.2.8
fail: heroku/nodejs-pnpm-install@3.2.8
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/nodejs-engine@3.2.8
fail: heroku/nodejs-pnpm-engine@3.2.8
fail: heroku/nodejs-pnpm-install@3.2.8
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/nodejs-engine@3.2.8
skip: heroku/nodejs-corepack@3.2.8
fail: heroku/nodejs-yarn@3.2.8
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/nodejs-engine@3.2.8
skip: heroku/nodejs-corepack@3.2.8
skip: heroku/nodejs-npm-engine@3.2.8
fail: heroku/nodejs-npm-install@3.2.8
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/nodejs-engine@3.2.8
skip: heroku/procfile@3.1.2
Resolving plan... (try #1)
fail: heroku/nodejs-engine@3.2.8 provides unused node
Resolving plan... (try #2)
fail: heroku/nodejs-engine@3.2.8 provides unused node
======== Results ========
pass: heroku/jvm@6.0.1
fail: heroku/maven@6.0.1
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/jvm@6.0.1
fail: heroku/gradle@6.0.1
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/jvm@6.0.1
fail: heroku/sbt@6.0.1
skip: heroku/procfile@3.1.2
======== Results ========
pass: heroku/go@0.4.1
skip: heroku/procfile@3.1.2
Resolving plan... (try #1)
fail: heroku/go@0.4.1 provides unused go
======== Output: heroku/php@0.2.0 ========
No PHP project files found.
======== Results ========
fail: heroku/php@0.2.0
skip: heroku/procfile@3.1.2
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

This is an absolute wall of text

##### Expected behavior

A warning:

```
WARNING: You are building an image named `./ruby-getting-started` this is also the name of a directory. Did you mean to run `pack build <args> --path ./ruby-getting-started?
```
---

##### pack info

```
$ pack report
Pack:
  Version:  0.34.2+git-ce8db3c.build-6005
  OS/Arch:  darwin/arm64

Default Lifecycle Version:  0.19.6

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13

Config:
  default-builder-image = "[REDACTED]"
```

### PR DESCRIPTION
**Pull request by hhiroshell**
## Summary
This PR makes the `pack build` warn that the positional argument specifying the image name will not be treated as the source directory path, addressing https://github.com/buildpacks/pack/issues/2231.

#### Before

```console
$ pack build sample-app --builder cnbs/sample-builder:jammy
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

#### After

`pack build` warns it if both of the following criteria are met:
- The build artifact is not specified as an OCI file layout.
- The `--path` flag is not used.

```console
$ pack build sample-app --builder cnbs/sample-builder:jammy
Warning: You are building an image named 'sample-app'. If you mean it as an app directory path, run 'pack build <args> --path sample-app'
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

`pack build` doesn't warn it if the build artifact is specified as an OCI file layout.

```console
$ pack config experimental true
Experimental features enabled!

$ pack build oci:sample-app --builder cnbs/sample-builder:jammy
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

`pack build` doesn't warn it if the `--path` flag is specified.

```console
$ pack build sample-app --builder cnbs/sample-builder:jammy --path apps/java-maven
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #2231

### CODE REVIEW

File: internal/commands/build_test.go [hunk 1]
```diff
@@ -77,6 +76,7 @@ func testBuildCommand(t *testing.T, when spec.G, it spec.S) {
 
 				command.SetArgs([]string{"--builder", "my-builder", "image"})
 				h.AssertNil(t, command.Execute())
+				h.AssertContains(t, outBuf.String(), "Warning: You are building an image named 'image'. If you mean it as an app directory path, run 'pack build <args> --path image'")
```
Comment (hhiroshell) [inline internal/commands/build_test.go:79]: Note:
I've added this assertion only to this case since asserting it in all applicable cases would be too noisy. Please let me know if you have any thoughts.

**Comment by hhiroshell** [comment]
I'm thinking about adding some test cases for when the `pack build` is executed with the `--path` flag. 
Please give me some time before proceeding with the review.

**Comment by hhiroshell** [comment]
All the changes are complete, so please review them!

File: internal/commands/build.go [hunk 2]
```diff
@@ -328,6 +327,11 @@ func validateBuildFlags(flags *BuildFlags, cfg config.Config, inputImageRef clie
 		return client.NewExperimentError("Exporting to OCI layout is currently experimental.")
 	}
 
+	if !inputImageRef.Layout() && flags.AppPath == "" {
```
Comment (natalieparellano) [inline internal/commands/build.go:330]: I fear that adding this warning to all cases under this condition would be too noisy. `pack build my-app` is a very common (and recommended) invocation. I think we should only warn when `my-app` happens to be a local path. 

This should do the trick:

```
if _, err := os.Stat(inputImageRef.Name()); err == nil {
    // image name exists as a local path, warn
}
```

We probably don't need to check `inputImageRef.Layout()` because those refs will always start with `oci://` I'm pretty sure

Comment (hhiroshell) [reply internal/commands/build.go:330]: Thank you for your suggestion. I like your idea of avoiding warnings every time users run pack build.👍

**Comment by hhiroshell** [comment]
With the latest commits I made, the behavior of the `pack build` has changed as below:

`pack build` warns it if both of the following criteria are met:
- A local path with the same string as the specified image name exists
- The `--path` flag is not used.

```console
$ test -e apps/java-maven && echo "exists" || echo "does not exist"
exists

$ pack build apps/java-maven --builder cnbs/sample-builder:jammy
Warning: You are building an image named 'apps/java-maven'. If you mean it as an app directory path, run 'pack build <args> --path apps/java-maven'
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

`pack build` doesn't warn it if a local path with the same string as the specified image name __doesn't exist__.

```console
$ test -e aaaa && echo "exists" || echo "does not exist"
does not exist

$ pack build aaaa --builder cnbs/sample-builder:jammy
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

`pack build` doesn't warn it if a local path with the same string as the specified image name exists, and `--path` is used.

```console
$ test -e apps/java-maven && echo "exists" || echo "does not exist"
exists

$ pack build apps/java-maven --path apps/java-maven --builder cnbs/sample-builder:jammy
jammy: Pulling from cnbs/sample-builder
Digest: sha256:9db376e26252b6cbc75190c88ea24571da36ec0d373136be233b32fd174962fc
Status: Image is up to date for cnbs/sample-builder:jammy
...
```

File: internal/commands/build_test.go [hunk 3]
```diff
@@ -931,6 +930,56 @@ builder = "my-builder"
...
+			})
+		})
+
+		when("a local path with the same string as the specified image name exists", func() {
+			var dir string
+
+			it.Before(func() {
+				// avoid using paths generated by os.MkdirTemp() as they cause test failures on macOS.
+				dir = "my-app-dir" + h.RandString(8)
+				err := os.Mkdir(dir, 0700)
```
Comment (hhiroshell) [inline internal/commands/build_test.go:950]: A path created by os.MkdirTemp() on macOS is like: `/var/folders/vh/0l94sp8n6hx8qwhb6wsy_xrh0000gr/T/tmp.4ffiJJd5rq`
It triggers an error in the validation of the image name when specified as a positional argument (image name).

**Comment by hhiroshell** [comment]
@natalieparellano 
I believe all comments have been resolved. Would you please confirm that?

If I need to explain some recent changes (https://github.com/buildpacks/pack/pull/2256#issuecomment-2354470291,  https://github.com/buildpacks/pack/pull/2256#discussion_r1764824634 ), I'll happily do so. So please let me know.

File: internal/commands/build_test.go (hunk 3 above)
Comment (jjbustamante) [reply internal/commands/build_test.go:950]: Are we creating the `my-app-dir` folder in the current directory? if for some reason the test fails and I am running the tests locally, will I see this new `my-app-dir` like a new file not being tracked by git?

Comment (natalieparellano) [reply internal/commands/build_test.go:950]: I agree that creating a new directory in the local source is a bit weird. An alternative would be to invoke `pack build testdata` since (I'm pretty sure) this test runs in the context of <pack source root>/internal/commands/. We could also try some combination of `os.MkdirTemp` and `os.Chdir` to create a directory with a sensible reference, but that might be a bit heavy-handed for what we need.

**Comment by natalieparellano** [comment]
@hhiroshell thank you for your work on this, and apologies for being slow to get back to you with a review. I think we should address the concern here: https://github.com/buildpacks/pack/pull/2256#discussion_r1784646025 (added some suggestions)

File: internal/commands/build_test.go (hunk 3 above)
Comment (hhiroshell) [reply internal/commands/build_test.go:950]: @jjbustamante @natalieparellano 
Thank you for your comments and suggestions! I'll try to fix it to use the `testdata`. 🙏

Comment (hhiroshell) [reply internal/commands/build_test.go]: Done: https://github.com/buildpacks/pack/pull/2256/commits/3aee96ea4f82385680d76108099c24b393182fea

Now the code looks clean, and there will be no residue left in case of test failures. 😌

**Comment by natalieparellano** [comment]
LCOW failure seems unrelated, we are looking into it...

**Comment by hhiroshell** [comment]
Thank you for your effort, @natalieparellano.
If there is anything I can do, please let me know.

**Review by natalieparellano — APPROVED** [review]

**Comment by hhiroshell** [comment]
@natalieparellano @jjbustamante 
Thank you for all your effort in reviewing and fixing the CI failure. I'm honored to have my PR merged!

**Comment by natalieparellano** [comment]
Thank you for your contribution @hhiroshell!
