### PR TITLE
Pass --volume options to creator phase

### LINKED ISSUE #674: Pack doesn't mount provided volume when using creator
### Summary
When building an image using a trusted builder pack now uses a single `creator` lifecycle phase container to perform all operations. When the `--volume` argument is passed, this is generally used to instantiate containers for the individual phases that need it. This argument is currently not being respected when initializing a `creator` phase.

---

##### Steps
1. If we return the [acceptance tests for mounting volumes](https://github.com/buildpacks/pack/blob/master/acceptance/acceptance_test.go#L967-L970) to their original states, expecting the messages to include the file contents `some-string` the tests will fail
2. 
```
...
---> DETECTING
        ======== Output: volume/bp@volume-bp-version ========
        ---> Detect: Volume Buildpack
        /cnb/buildpacks/volume_bp/volume-bp-version/bin/detect: line 9: /platform/my-volume-mount-target/some-file: No such file or directory
        Detect: Reading file '/platform/my-volume-mount-target/some-file':
        ---> Done
        ...
        ---> BUILDING
        ---> Build: Volume Buildpack
        /cnb/buildpacks/volume_bp/volume-bp-version/bin/build: line 9: /platform/my-volume-mount-target/some-file: No such file or directory
        Build: Reading file '/platform/my-volume-mount-target/some-file':
        ---> Done
...
to contain 'Detect: Reading file '/platform/my-volume-mount-target/some-file': some-string'
...
```

##### Current behavior
Creator is not mounted with the expected bind configured with `--volume` leading a buildpack that expects to find mounted content unable to read it.

##### Expected behavior
Creator is mounted with the bind configured with `--volume`, a buildpack can read content from this volume

---

### Environment

Acceptance tests

### PR DESCRIPTION
**Pull request by simonjjones**
This resolves a bug where we weren't configuring the `creator` phase with any binds configured with the `--volume` option

Resolves #674

Signed-off-by: Simon Jones <simonjones@vmware.com>

### CODE REVIEW

File: internal/build/phases_test.go [hunk 1]
```diff
@@ -88,19 +110,65 @@ func testPhases(t *testing.T, when spec.G, it spec.S) {
...
+				[]string{},
+				fakePhaseFactory,
+			)
 			h.AssertNil(t, err)
 
 			configProvider := fakePhaseFactory.NewCalledWithProvider
 			h.AssertEq(t, configProvider.HostConfig().NetworkMode, container.NetworkMode(expectedNetworkMode))
 		})
 
+		it("configures the phase with both cache binds and custom volume mounts", func() {
```
Comment (yaelharel) [inline internal/build/phases_test.go:131]: Since you added this check, maybe we can remove the tests on lines 212 and 332

File: acceptance/acceptance_test.go [hunk 2]
```diff
@@ -950,10 +957,10 @@ func testAcceptance(
 						})
 
 						it.After(func() {
-							h.AssertNil(t, os.Remove(buildpackTgz))
-							h.AssertNil(t, h.DockerRmi(dockerCli, repoName))
+							_ = os.Remove(buildpackTgz)
+							_ = h.DockerRmi(dockerCli, repoName)
 
-							h.AssertNil(t, os.RemoveAll(tempVolume))
+							_ = os.RemoveAll(tempVolume)
```
[the remark this answers is not in the document]
Comment (simonjjones) [reply acceptance/acceptance_test.go:963]: The test is now skippable, so cleanup can reasonably expect to fail when it's skipped

File: internal/build/phases_test.go (hunk 1 above)
Comment (simonjjones) [reply internal/build/phases_test.go:131]: They still test slightly different circumstances - the difference between publish and not, as well as ensuring the cache binds will be configured regardless of whether a custom volume is configured.

File: acceptance/acceptance_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (yaelharel) [reply acceptance/acceptance_test.go:963]: You're right! Thanks for the clarification!

File: internal/build/phases_test.go (hunk 1 above)
Comment (yaelharel) [reply internal/build/phases_test.go:131]: You're right but I'm not sure if I would keep all 3 tests. I think it's a little confusing that we're testing part of it 3 times.
Maybe we change this test to test only the configuration with custom volume mounts, and to keep the other tests to test only the cache and launch-cache.
What do you think about that?

Comment (simonjjones) [reply internal/build/phases_test.go]: I opted to remove this test, and add custom volume mounts to the existing bind tests which cover both the `publish=true` and `publish=false` contexts.

**Comment by jromero** [comment]
# ✔️ Accepted

```
./out/pack build some-app -v -B cnbs/sample-builder:alpine -p ../samples/apps/bash-script/ --volume /tmp/some-dir:/my-dir --trust-builder
Using project descriptor located at ../samples/apps/bash-script/project.toml
Pulling image index.docker.io/cnbs/sample-builder:alpine
alpine: Pulling from cnbs/sample-builder
Digest: sha256:eaf42c17a45bfa6bcf5b73fe4f1d64e36376dd91addb0872bd5911628f71fb91
Status: Image is up to date for cnbs/sample-builder:alpine
Selected run image cnbs/sample-stack-run:alpine
Pulling image cnbs/sample-stack-run:alpine
alpine: Pulling from cnbs/sample-stack-run
Digest: sha256:5832173333c36b98b3ab47b7dc97248f3d9e297973c136f47171776b2950dedd
Status: Image is up to date for cnbs/sample-stack-run:alpine
Adding buildpack samples/bash-script version 0.0.1 to builder
Setting custom order
Creating builder with the following buildpacks:
-> samples/java-maven@0.0.1
-> samples/kotlin-gradle@0.0.1
-> samples/hello-universe@0.0.1
-> samples/hello-moon@0.0.1
-> samples/hello-world@0.0.1
-> samples/bash-script@0.0.1
Using build cache volume pack-cache-891d1f8dedc9.build
---> DETECTING
======== Output: samples/bash-script@0.0.1 ========
---> Hello Bash Script buildpack

Here are the contents of the current working directory:
.:
total 16
drwxr-xr-x    2 cnb      cnb           4096 Jun  8 19:24 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
-rwxr-xr-x    1 cnb      cnb            738 Apr  6 23:13 app.sh
-rw-r--r--    1 cnb      cnb            202 Apr  6 23:13 project.toml
Here are the contents of /platform:
/platform:
total 12
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
drwxr-xr-x    1 root     root          4096 Jan  1  1980 env
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 my-dir

/platform/env:
total 8
drwxr-xr-x    1 root     root          4096 Jan  1  1980 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..

/platform/my-dir:
total 4
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
drwxr-xr-x    3 cnb      cnb             96 Jun  8 19:23 other-dir
-rw-r--r--    1 cnb      cnb              0 Jun  8 19:22 some-file

/platform/my-dir/other-dir:
total 0
drwxr-xr-x    3 cnb      cnb             96 Jun  8 19:23 .
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 ..
-rw-r--r--    1 cnb      cnb              0 Jun  8 19:23 other-file
======== Results ========
pass: samples/bash-script@0.0.1
Resolving plan... (try #1)
samples/bash-script 0.0.1
---> ANALYZING
Analyzing image "ce0aa8dbf65c9bfa8fc47bb1a39e3bbea4635c47a8b88a3b1730a309a4ab9451"
---> RESTORING
---> BUILDING
---> Hello World buildpack
---> Hello Bash Script buildpack

Here are the contents of the current working directory:
.:
total 16
drwxr-xr-x    2 cnb      cnb           4096 Jun  8 19:24 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
-rwxr-xr-x    1 cnb      cnb            738 Apr  6 23:13 app.sh
-rw-r--r--    1 cnb      cnb            202 Apr  6 23:13 project.toml
Here are the contents of /platform:
/platform:
total 12
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
drwxr-xr-x    1 root     root          4096 Jan  1  1980 env
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 my-dir

/platform/env:
total 8
drwxr-xr-x    1 root     root          4096 Jan  1  1980 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..

/platform/my-dir:
total 4
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 .
drwxr-xr-x    1 root     root          4096 Jun  8 19:24 ..
drwxr-xr-x    3 cnb      cnb             96 Jun  8 19:23 other-dir
-rw-r--r--    1 cnb      cnb              0 Jun  8 19:22 some-file

/platform/my-dir/other-dir:
total 0
drwxr-xr-x    3 cnb      cnb             96 Jun  8 19:23 .
drwxr-xr-x    4 cnb      cnb            128 Jun  8 19:23 ..
-rw-r--r--    1 cnb      cnb              0 Jun  8 19:23 other-file
---> EXPORTING
no project metadata found at path './project-metadata.toml', project metadata will not be exported
Reusing layers from image with id 'ce0aa8dbf65c9bfa8fc47bb1a39e3bbea4635c47a8b88a3b1730a309a4ab9451'
Writing tarball for layer "launcher"
Reusing layer 'launcher'
Layer 'launcher' SHA: sha256:32608bc6d97e0193edb0360555b3e08dc6dfe1187833d8548cdd9e662213935b
Layer 'app' SHA: sha256:4c6ff16e28deaf437a1abe5c926cdfb8afcd2c31ea544f6992ed7b665965b3f4
Reusing 1/1 app layer(s)
Writing tarball for layer "config"
Reusing layer 'config'
Layer 'config' SHA: sha256:ed89d623eb7cf47a03403af0b6d3723a967ca4f73985b97056246193d29eb3b0
*** Images (ce0aa8dbf65c):
      index.docker.io/library/some-app:latest

*** Image ID: ce0aa8dbf65c9bfa8fc47bb1a39e3bbea4635c47a8b88a3b1730a309a4ab9451
Successfully built image some-app
```
