### PR TITLE
Fix duplicate detection and content collision

### LINKED ISSUE #1081: pack builder create adds duplicate buildpack layers
### Summary
When creating a builder that contains multiple metabuildpacks, each of which contains the same component buildpack, multiple copies of the component buildpack are added to the builder. This results in builder images that are much larger than they need to be.

Each buildpack, identified by an id/version pair, should only be added to the builder once. This should also be applied to buildpacks provided to `pack build` with the `--buildpack` flag. If the provided buildpack is a metabuildpack that contains components that already exist on the builder, only add the missing layers.

---

##### Steps

1. `git clone git@github.com:paketo-buildpacks/full-builder.git`
1. `cd full-builder`
1. `pack create-builder test/builder -c builder.toml`
1. `docker inspect test/builder`

##### Current behavior
This image shows a snippet of the docker inspect output highlighting, duplicate layers containing `paketo-buildpacks/procfile@4.0.0`

Screen Shot 2021-02-17 at 5 51 18 PM

##### Expected behavior
Exactly one copy of the layer containing `paketo-buildpacks/procfile@4.0.0`.

---

##### pack info
```
pack version
0.17.0+git-d9cb4e7.build-2045
```

##### docker info
N/A

### LINKED ISSUE #1108: pack builder create should successfully overwrite pre-existing buildpacks
### Summary

Currently, if buildpack layers with the same `id@version` but different contents are provided while creating a builder the following error is presented:

```
ERROR: failed to write image to the following tags: [test-heroku:20: image load 'test-heroku:20'. first error: embedded daemon response: invalid diffID for layer 15: expected "sha256:a02d3fde2aeb174a2aa54081c66d4ca7c61859ee120516d71817089c8236fa2e", got "sha256:57a49fb084ace8d18b8b39aa70204f1e5f3b1ec979549e0805e63f11dd101e68"]
exit status 1
```

##### Additional Context

- Slack discussion: https://buildpacks.slack.com/archives/CD61YAG69/p1615323343013800
- Related to https://github.com/buildpacks/pack/issues/1081

---

##### Steps

1. Create `builder.toml`:
    
```
description = "Base builder for Heroku-20 stack, based on ubuntu:20.04 base image"
[stack]
id = "heroku-20"
build-image = "heroku/pack:20-build"
run-image = "heroku/pack:20"
[lifecycle]
version = "0.10.1"
[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/r2f9u0w4/heroku-java-buildpack@sha256:b047016825aef50813d1077bf2d541362390d2018ea8485d622a9e0fa381a25d"
[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.6.1"
```
2. `pack builder create test-heroku:20 -c builder.toml -v`

##### Current behavior

```

ERROR: failed to write image to the following tags: [test-heroku:20: image load 'test-heroku:20'. first error: embedded daemon response: invalid diffID for layer 15: expected "sha256:a02d3fde2aeb174a2aa54081c66d4ca7c61859ee120516d71817089c8236fa2e", got "sha256:57a49fb084ace8d18b8b39aa70204f1e5f3b1ec979549e0805e63f11dd101e68"]
exit status 1
```

DATA:

```
Image: 
docker://public.ecr.aws/r2f9u0w4/heroku-java-buildpack@sha256:b047016825aef50813d1077bf2d541362390d2018ea8485d622a9e0fa381a25d
Procfile layer:
- Index = 3
- Dive ID: 18007ad0ce852c53382104a7614dec13ff773bdaf84a5190b78ce4e3e2f3275e
- Dive Digest: sha256:a02d3fde2aeb174a2aa54081c66d4ca7c61859ee120516d71817089c8236fa2e
- Size: 3.3 MB

Image:
docker://docker.io/heroku/procfile-cnb:0.6.1
Procfile layer:
- Index = 0
- Dive ID: ef7254292d24823c1d2229a7214edb4d4744eade8927bada629be5aa71aa973d
- Dive Digest: sha256:57a49fb084ace8d18b8b39aa70204f1e5f3b1ec979549e0805e63f11dd101e68
- Size: 3.3 MB
```

##### Expected behavior

```
Warning: buildpack heroku/procfile@0.6.1 already exists on builder and will be overwritten
    - Previous Digest: sha256:A...
    - New Digest: sha256:B...
Successfully created builder image test-heroku:20
Tip: Run pack build <image-name> --builder test-heroku:20 to use this builder
```

---

##### pack info

```
Pack:
  Version:  0.17.0+git-d9cb4e7.build-2045
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.10.2

Supported Platform APIs:  0.3, 0.4

Config:
  experimental = true
  run-images = []
  lifecycle-image = "buildpacksio/lifecycle:0.10.1"

  [[trusted-builders]]
    name = "my-builder"

```

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 5
  Running: 2
  Paused: 0
  Stopped: 3
 Images: 131
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: KHK5:J3RQ:RITQ:3DKV:SFYA:EEQG:2MAE:CMVS:TTJZ:3J6B:NQR4:QOHZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker.for.mac.localhost:5000
  host.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false


```

### PR DESCRIPTION
**Pull request by jromero**
## Summary

Fix duplicate detection and content collision

#### After

[asciicast](https://asciinema.org/a/15oYIFTOCbu5ow3oe0JUYZoKu)

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No

## Related

Resolves #1081
Resolves #1108

### CODE REVIEW

File: internal/builder/builder.go [hunk 1]
```diff
@@ -394,6 +367,94 @@ func (b *Builder) Save(logger logging.Logger, creatorMetadata CreatorMetadata) e
...
+	buildpacksToAdd := map[string]buildpackToAdd{}
+	for i, bp := range additionalBuildpacks {
+		// create buildpack directory
+		bpTmpDir := filepath.Join(tmpDir, strconv.Itoa(i))
+		if err := os.MkdirAll(bpTmpDir, os.ModePerm); err != nil {
+			return errors.Wrap(err, "creating buildpack temp dir")
+		}
+
+		// create tar file
+		bpLayerTar, err := dist.BuildpackToLayerTar(bpTmpDir, bp)
```
Comment (jromero) [inline internal/builder/builder.go:386]: This additional nested indexed directory prevents multiple buildpacks with the same id + version from colliding based on how `BuildpackToLayerTar` works.

File: acceptance/acceptance_test.go [hunk 2]
```diff
@@ -704,6 +704,64 @@ func testAcceptance(
...
+					// looks like this is used to de-dup tasks
+					key := taskKey(
+						"create-complex-builder",
+						append(
+							[]string{runImageMirror, createBuilderPackConfig.Path(), lifecycle.Identifier()},
+							createBuilderPackConfig.FixturePaths()...,
+						)...,
+					)
+					// run task on taskmanager and save output, in case there are future calls to the same task
+					// likely all our changes need to go on the createBuilderPack.
```
Comment (dfreilich) [inline acceptance/acceptance_test.go:723]: nit: remove this line

File: acceptance/acceptance_test.go [hunk 3]
```diff
@@ -704,6 +704,64 @@ func testAcceptance(
...
+						assert.Nil(err)
+
+						layerSet := map[string]interface{}{}
+						for _, layer := range out.RootFS.Layers {
+							_, ok := layerSet[layer]
+							if ok {
+								t.Fatalf("duplicate layer found in builder %s", layer)
+							}
+							layerSet[layer] = true
+						}
```
Comment (dfreilich) [inline acceptance/acceptance_test.go:760]: Can this be moved into the `ImageAssertionManager` (https://github.com/buildpacks/pack/blob/main/acceptance/assertions/image.go#L13-L18)? It could be useful for reuse and for clarity

File: internal/builder/builder.go [hunk 4]
```diff
@@ -300,36 +300,9 @@ func (b *Builder) Save(logger logging.Logger, creatorMetadata CreatorMetadata) e
...
-			logger.Debugf(
-				"buildpack %s already exists on builder and will be overwritten",
-				style.Symbol(bpInfo.FullName()),
-			)
-		}
-
-		dist.AddBuildpackToLayersMD(bpLayers, bp.Descriptor(), diffID.String())
+	err = addBuildpacks(logger, tmpDir, b.image, b.additionalBuildpacks, bpLayers)
+	if err != nil {
+		return err
```
Comment (dfreilich) [inline internal/builder/builder.go:305]: 🥳 🥳 🥳 
Great job cleaning this up

File: internal/builder/builder.go [hunk 5]
```diff
@@ -394,6 +367,94 @@ func (b *Builder) Save(logger logging.Logger, creatorMetadata CreatorMetadata) e
...
+
+			logger.Debugf(
+				`buildpack %s was previously defined with different contents
+  - previous diffID: %s
+  - using diffID: %s`,
+				style.Symbol(bpInfo.FullName()),
+				style.Symbol(otherAdditionalBP.diffID),
+				style.Symbol(diffID.String()),
+			)
+		}
```
Comment (dfreilich) [inline internal/builder/builder.go:433]: Is there some way we can collapse these two, or make the contents of the `if` funcs equivalent so it can be pulled out and reused? It makes the method much more intimidatingly long.

**Review by dfreilich — CHANGES_REQUESTED** [review]
Overall, this is super great! A few nits that I'd like to see addressed before this is merged in, but

File: internal/builder/builder.go (hunk 5 above)
Comment (dwillist) [reply internal/builder/builder.go]: Simplified the error message itself, but I couldn't see a clean way to combine the `if` statements here ☹️

**Review by dfreilich — APPROVED** [review]
