### PR TITLE
Buildpack URL formatted incorrect when using a registry mirror

### LINKED ISSUE #1618: Buildpack URL formatted incorrect when using a registry mirror
### Summary

When using a registry mirror, I get the following error:

```
ERROR: failed to build: downloading buildpack: extracting from registry urn:cnb:registry:heroku/ruby: fetching image: could not parse reference: registry.apppackcdn.net/heroku/buildpack-ruby:sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
```

The reference does look incorrect, I can confirm via:

```
$ docker pull registry.apppackcdn.net/heroku/buildpack-ruby:sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
invalid reference format
```

Replacing the first `:` with an `@` allows me to pull the image:

```
$ docker pull registry.apppackcdn.net/heroku/buildpack-ruby@sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
# image pulls successfully
```

---

##### Steps

```
$ pack config registry-mirrors add index.docker.io --mirror registry.apppackcdn.net
$ pack build -b urn:cnb:registry:heroku/ruby -B heroku/buildpacks:20 test
```

##### Current behavior

Build fails with error:

```
ERROR: failed to build: downloading buildpack: extracting from registry urn:cnb:registry:heroku/ruby: fetching image: could not parse reference: registry.apppackcdn.net/heroku/buildpack-ruby:sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
```

##### Expected behavior

Build to complete successfully as it does without a mirror

---

##### pack info

```
Pack:
  Version:  0.28.0+git-b10e41f.build-3729
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.15.2

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10

Config:
  [registry-mirrors]
    "index.docker.io" = "registry.apppackcdn.net"
```

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 24
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.22GiB
 Name: ll-server
 ID: S4IG:47J6:2P4Z:YWAT:TFGO:DSH7:UGNH:IB6N:UMEO:NIIW:ST3Q:LUC3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by jjbustamante**
## Summary
When a mirror is used and a buildpack that points to a digest reference must be downloaded, pack is not parsing correctly the digest.

## Output
No errors are thrown

#### Before

``` =bash
ERROR: failed to build: downloading buildpack: extracting from registry urn:cnb:registry:heroku/ruby: fetching image: could not parse reference: registry.apppackcdn.net/heroku/buildpack-ruby:sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
```

#### After

``` =bash
Digest: sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
Status: Downloaded newer image for registry.apppackcdn.net/heroku/buildpack-ruby@sha256:7f48a442c056cd19ea48462e05faa2837ac3a13732c47616d20f11f8c847a8c4
Using mirror registry.apppackcdn.net/heroku/heroku:20-cnb for heroku/heroku:20-cnb
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1618 

Signed-off-by: Juan Bustamante <jbustamante@vmware.com>

### CODE REVIEW

File: internal/name/name.go [hunk 1]
```diff
@@ -2,17 +2,24 @@ package name
...
+	defaultRefFormat = "%s/%s:%s"
+	digestRefFormat  = "%s/%s@%s"
+)
+
 type Logger interface {
 	Infof(fmt string, v ...interface{})
 }
 
 func TranslateRegistry(name string, registryMirrors map[string]string, logger Logger) (string, error) {
+	logger.Infof("input %s", name)
```
Comment (jjbustamante) [inline internal/name/name.go:22]: I will remove this.

**Review by dfreilich — APPROVED** [review]
