### PR TITLE
`pack report` should not display error when config.toml is not present

### LINKED ISSUE #433: `pack report` should not display error when config.toml is not present
Currently it seems misleading that we display an "error" when pack's config.toml is not present.

For example,
```
root@45fa57ec-7290-4959-619c-6c1af8ba6ada:/tmp/build/59a8880f# ./pack-cli/pack report
Pack:
  Version:  v0.6.0 (git sha: 109b629d388cec0ed3836b9fed6717727a9187c1)
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.5.0

Config:
(error: open /root/.pack/config.toml: no such file or directory)
```

Expected output:

```
root@45fa57ec-7290-4959-619c-6c1af8ba6ada:/tmp/build/59a8880f# ./pack-cli/pack report
Pack:
  Version:  v0.6.0 (git sha: 109b629d388cec0ed3836b9fed6717727a9187c1)
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.5.0

Config:
(no config file found at /root/.pack/config.toml)
```

### PR DESCRIPTION
**Pull request by ktpv**
fixes #433

### CODE REVIEW

File: internal/commands/report.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ import (
 	"github.com/buildpacks/pack/logging"
 )
 
-func Report(logger logging.Logger) *cobra.Command {
+func Report(logger logging.Logger, client PackClient) *cobra.Command {
```
Comment (jromero) [inline internal/commands/report.go]: This seems to go unused. What's the purpose of passing it in?

File: internal/commands/report_test.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+		when("config.toml is not present", func() {
+			it.Before(func() {
+				os.Setenv("PACK_HOME", packMissingHome)
+			})
+			it.After(func() {
+				os.Unsetenv("PACK_HOME")
+			})
+			it("logs a message", func() {
+				h.AssertNil(t, command.Execute())
+				h.AssertContains(t, outBuf.String(), fmt.Sprintf("(no config file found at %s"+string(filepath.Separator)+"config.toml)", packMissingHome))
```
Comment (jromero) [inline internal/commands/report_test.go]: This would be slightly cleaner as:

```
h.AssertContains(t, outBuf.String(), fmt.Sprintf("(no config file found at %s)", filpath.Join(packMissingHome, "config.tom"))
```

Comment (ktpv) [reply internal/commands/report_test.go]: Change made.

File: internal/commands/report.go (hunk 1 above)
Comment (ktpv) [reply internal/commands/report.go]: Removed.
